// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpcpb/services.proto

package rpcpb

import (
	clientpb "github.com/sudosoc/SUDOSOC-C2/protobuf/clientpb"
	commonpb "github.com/sudosoc/SUDOSOC-C2/protobuf/commonpb"
	sudosocpb "github.com/sudosoc/SUDOSOC-C2/protobuf/sudosocpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcpb_services_proto protoreflect.FileDescriptor

const file_rpcpb_services_proto_rawDesc = "" +
	"\n" +
	"\x14rpcpb/services.proto\x12\x05rpcpb\x1a\x15commonpb/common.proto\x1a\x15sudosocpb/sudosoc.proto\x1a\x15clientpb/client.proto2\xec\\\n" +
	"\tCoreRPC\x120\n" +
	"\n" +
	"GetVersion\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Version\x127\n" +
	"\tClientLog\x12\x17.clientpb.ClientLogData\x1a\x0f.commonpb.Empty(\x01\x124\n" +
	"\fGetOperators\x12\x0f.commonpb.Empty\x1a\x13.clientpb.Operators\x12*\n" +
	"\x04Kill\x12\x11.sudosocpb.KillReq\x1a\x0f.commonpb.Empty\x12>\n" +
	"\vReconfigure\x12\x18.sudosocpb.ReconfigureReq\x1a\x15.sudosocpb.Reconfigure\x12.\n" +
	"\x06Rename\x12\x13.clientpb.RenameReq\x1a\x0f.commonpb.Empty\x122\n" +
	"\vGetSessions\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Sessions\x123\n" +
	"\fMonitorStart\x12\x0f.commonpb.Empty\x1a\x12.commonpb.Response\x12/\n" +
	"\vMonitorStop\x12\x0f.commonpb.Empty\x1a\x0f.commonpb.Empty\x12C\n" +
	"\x11MonitorListConfig\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.MonitoringProviders\x12D\n" +
	"\x10MonitorAddConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Response\x12D\n" +
	"\x10MonitorDelConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Response\x12>\n" +
	"\x0eGetAIProviders\x12\x0f.commonpb.Empty\x1a\x1b.clientpb.AIProviderConfigs\x12@\n" +
	"\x12GetAIConversations\x12\x0f.commonpb.Empty\x1a\x19.clientpb.AIConversations\x12J\n" +
	"\x11GetAIConversation\x12\x1b.clientpb.AIConversationReq\x1a\x18.clientpb.AIConversation\x12H\n" +
	"\x12SaveAIConversation\x12\x18.clientpb.AIConversation\x1a\x18.clientpb.AIConversation\x12D\n" +
	"\x14DeleteAIConversation\x12\x1b.clientpb.AIConversationReq\x1a\x0f.commonpb.Empty\x12Z\n" +
	"\x19GetAIConversationMessages\x12\x1b.clientpb.AIConversationReq\x1a .clientpb.AIConversationMessages\x12]\n" +
	"\x19SaveAIConversationMessage\x12\x1f.clientpb.AIConversationMessage\x1a\x1f.clientpb.AIConversationMessage\x12E\n" +
	"\x11StartMTLSListener\x12\x19.clientpb.MTLSListenerReq\x1a\x15.clientpb.ListenerJob\x12A\n" +
	"\x0fStartWGListener\x12\x17.clientpb.WGListenerReq\x1a\x15.clientpb.ListenerJob\x12C\n" +
	"\x10StartDNSListener\x12\x18.clientpb.DNSListenerReq\x1a\x15.clientpb.ListenerJob\x12F\n" +
	"\x12StartHTTPSListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x12E\n" +
	"\x11StartHTTPListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x120\n" +
	"\n" +
	"GetBeacons\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Beacons\x12/\n" +
	"\tGetBeacon\x12\x10.clientpb.Beacon\x1a\x10.clientpb.Beacon\x12-\n" +
	"\bRmBeacon\x12\x10.clientpb.Beacon\x1a\x0f.commonpb.Empty\x129\n" +
	"\x0eGetBeaconTasks\x12\x10.clientpb.Beacon\x1a\x15.clientpb.BeaconTasks\x12B\n" +
	"\x14GetBeaconTaskContent\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12>\n" +
	"\x10CancelBeaconTask\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12N\n" +
	" UpdateBeaconIntegrityInformation\x12\x19.clientpb.BeaconIntegrity\x1a\x0f.commonpb.Empty\x12*\n" +
	"\aGetJobs\x12\x0f.commonpb.Empty\x1a\x0e.clientpb.Jobs\x122\n" +
	"\aKillJob\x12\x14.clientpb.KillJobReq\x1a\x11.clientpb.KillJob\x127\n" +
	"\vRestartJobs\x12\x17.clientpb.RestartJobReq\x1a\x0f.commonpb.Empty\x12O\n" +
	"\x16StartTCPStagerListener\x12\x1b.clientpb.StagerListenerReq\x1a\x18.clientpb.StagerListener\x12)\n" +
	"\aLootAdd\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12)\n" +
	"\x06LootRm\x12\x0e.clientpb.Loot\x1a\x0f.commonpb.Empty\x12,\n" +
	"\n" +
	"LootUpdate\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n" +
	"\vLootContent\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n" +
	"\aLootAll\x12\x0f.commonpb.Empty\x1a\x11.clientpb.AllLoot\x12/\n" +
	"\x05Creds\x12\x0f.commonpb.Empty\x1a\x15.clientpb.Credentials\x122\n" +
	"\bCredsAdd\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x121\n" +
	"\aCredsRm\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x125\n" +
	"\vCredsUpdate\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x129\n" +
	"\vGetCredByID\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12A\n" +
	"\x12GetCredsByHashType\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12J\n" +
	"\x1bGetPlaintextCredsByHashType\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12@\n" +
	"\x12CredsSniffHashType\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12,\n" +
	"\x05Hosts\x12\x0f.commonpb.Empty\x1a\x12.clientpb.AllHosts\x12&\n" +
	"\x04Host\x12\x0e.clientpb.Host\x1a\x0e.clientpb.Host\x12)\n" +
	"\x06HostRm\x12\x0e.clientpb.Host\x1a\x0f.commonpb.Empty\x12+\n" +
	"\tHostIOCRm\x12\r.clientpb.IOC\x1a\x0f.commonpb.Empty\x125\n" +
	"\bGenerate\x12\x15.clientpb.GenerateReq\x1a\x12.clientpb.Generate\x12L\n" +
	"\x15GenerateSpoofMetadata\x12\".clientpb.GenerateSpoofMetadataReq\x1a\x0f.commonpb.Empty\x12R\n" +
	"\x10GenerateExternal\x12\x1d.clientpb.ExternalGenerateReq\x1a\x1f.clientpb.ExternalImplantConfig\x12M\n" +
	"\x19GenerateExternalSaveBuild\x12\x1f.clientpb.ExternalImplantBinary\x1a\x0f.commonpb.Empty\x12Y\n" +
	"\x1eGenerateExternalGetBuildConfig\x12\x16.clientpb.ImplantBuild\x1a\x1f.clientpb.ExternalImplantConfig\x12?\n" +
	"\rGenerateStage\x12\x1a.clientpb.GenerateStageReq\x1a\x12.clientpb.Generate\x12?\n" +
	"\x11StageImplantBuild\x12\x19.clientpb.ImplantStageReq\x1a\x0f.commonpb.Empty\x12=\n" +
	"\x11GetHTTPC2Profiles\x12\x0f.commonpb.Empty\x1a\x17.clientpb.HTTPC2Configs\x12H\n" +
	"\x16GetHTTPC2ProfileByName\x12\x16.clientpb.C2ProfileReq\x1a\x16.clientpb.HTTPC2Config\x12?\n" +
	"\x11SaveHTTPC2Profile\x12\x19.clientpb.HTTPC2ConfigReq\x1a\x0f.commonpb.Empty\x127\n" +
	"\x0fBuilderRegister\x12\x11.clientpb.Builder\x1a\x0f.clientpb.Event0\x01\x122\n" +
	"\x0eBuilderTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bBuilders\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Builders\x12J\n" +
	"\x12GetCertificateInfo\x12\x19.clientpb.CertificatesReq\x1a\x19.clientpb.CertificateInfo\x12R\n" +
	"\x1bGetCertificateAuthorityInfo\x12\x0f.commonpb.Empty\x1a\".clientpb.CertificateAuthorityInfo\x128\n" +
	"\x05Crack\x12\x16.clientpb.CrackCommand\x1a\x17.clientpb.CrackResponse\x12A\n" +
	"\x14CrackstationRegister\x12\x16.clientpb.Crackstation\x1a\x0f.clientpb.Event0\x01\x127\n" +
	"\x13CrackstationTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12B\n" +
	"\x15CrackstationBenchmark\x12\x18.clientpb.CrackBenchmark\x1a\x0f.commonpb.Empty\x129\n" +
	"\rCrackstations\x12\x0f.commonpb.Empty\x1a\x17.clientpb.Crackstations\x129\n" +
	"\rCrackTaskByID\x12\x13.clientpb.CrackTask\x1a\x13.clientpb.CrackTask\x127\n" +
	"\x0fCrackTaskUpdate\x12\x13.clientpb.CrackTask\x1a\x0f.commonpb.Empty\x12;\n" +
	"\x0eCrackFilesList\x12\x13.clientpb.CrackFile\x1a\x14.clientpb.CrackFiles\x12;\n" +
	"\x0fCrackFileCreate\x12\x13.clientpb.CrackFile\x1a\x13.clientpb.CrackFile\x12A\n" +
	"\x14CrackFileChunkUpload\x12\x18.clientpb.CrackFileChunk\x1a\x0f.commonpb.Empty\x12L\n" +
	"\x16CrackFileChunkDownload\x12\x18.clientpb.CrackFileChunk\x1a\x18.clientpb.CrackFileChunk\x129\n" +
	"\x11CrackFileComplete\x12\x13.clientpb.CrackFile\x1a\x0f.commonpb.Empty\x127\n" +
	"\x0fCrackFileDelete\x12\x13.clientpb.CrackFile\x1a\x0f.commonpb.Empty\x129\n" +
	"\n" +
	"Regenerate\x12\x17.clientpb.RegenerateReq\x1a\x12.clientpb.Generate\x129\n" +
	"\rImplantBuilds\x12\x0f.commonpb.Empty\x1a\x17.clientpb.ImplantBuilds\x12:\n" +
	"\x12DeleteImplantBuild\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bCanaries\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Canaries\x12C\n" +
	"\x16GenerateWGClientConfig\x12\x0f.commonpb.Empty\x1a\x18.clientpb.WGClientConfig\x129\n" +
	"\x10GenerateUniqueIP\x12\x0f.commonpb.Empty\x1a\x14.clientpb.UniqueWGIP\x12=\n" +
	"\x0fImplantProfiles\x12\x0f.commonpb.Empty\x1a\x19.clientpb.ImplantProfiles\x12<\n" +
	"\x14DeleteImplantProfile\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12H\n" +
	"\x12SaveImplantProfile\x12\x18.clientpb.ImplantProfile\x1a\x18.clientpb.ImplantProfile\x12A\n" +
	"\fShellcodeRDI\x12\x19.clientpb.ShellcodeRDIReq\x1a\x16.clientpb.ShellcodeRDI\x122\n" +
	"\vGetCompiler\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Compiler\x12K\n" +
	"\x10ShellcodeEncoder\x12\x1c.clientpb.ShellcodeEncodeReq\x1a\x19.clientpb.ShellcodeEncode\x12E\n" +
	"\x13ShellcodeEncoderMap\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.ShellcodeEncoderMap\x12A\n" +
	"\x11TrafficEncoderMap\x12\x0f.commonpb.Empty\x1a\x1b.clientpb.TrafficEncoderMap\x12L\n" +
	"\x11TrafficEncoderAdd\x12\x18.clientpb.TrafficEncoder\x1a\x1d.clientpb.TrafficEncoderTests\x12=\n" +
	"\x10TrafficEncoderRm\x12\x18.clientpb.TrafficEncoder\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bWebsites\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Websites\x12/\n" +
	"\aWebsite\x12\x11.clientpb.Website\x1a\x11.clientpb.Website\x123\n" +
	"\rWebsiteRemove\x12\x11.clientpb.Website\x1a\x0f.commonpb.Empty\x12C\n" +
	"\x11WebsiteAddContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website\x12F\n" +
	"\x14WebsiteUpdateContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website\x12I\n" +
	"\x14WebsiteRemoveContent\x12\x1e.clientpb.WebsiteRemoveContent\x1a\x11.clientpb.Website\x12&\n" +
	"\x04Ping\x12\x0e.sudosocpb.Ping\x1a\x0e.sudosocpb.Ping\x12#\n" +
	"\x02Ps\x12\x0f.sudosocpb.PsReq\x1a\f.sudosocpb.Ps\x128\n" +
	"\tTerminate\x12\x16.sudosocpb.TerminateReq\x1a\x13.sudosocpb.Terminate\x125\n" +
	"\bIfconfig\x12\x15.sudosocpb.IfconfigReq\x1a\x12.sudosocpb.Ifconfig\x122\n" +
	"\aNetstat\x12\x14.sudosocpb.NetstatReq\x1a\x11.sudosocpb.Netstat\x12#\n" +
	"\x02Ls\x12\x0f.sudosocpb.LsReq\x1a\f.sudosocpb.Ls\x12$\n" +
	"\x02Cd\x12\x0f.sudosocpb.CdReq\x1a\r.sudosocpb.Pwd\x12&\n" +
	"\x03Pwd\x12\x10.sudosocpb.PwdReq\x1a\r.sudosocpb.Pwd\x12#\n" +
	"\x02Mv\x12\x0f.sudosocpb.MvReq\x1a\f.sudosocpb.Mv\x12#\n" +
	"\x02Cp\x12\x0f.sudosocpb.CpReq\x1a\f.sudosocpb.Cp\x12#\n" +
	"\x02Rm\x12\x0f.sudosocpb.RmReq\x1a\f.sudosocpb.Rm\x12,\n" +
	"\x05Mkdir\x12\x12.sudosocpb.MkdirReq\x1a\x0f.sudosocpb.Mkdir\x125\n" +
	"\bDownload\x12\x15.sudosocpb.DownloadReq\x1a\x12.sudosocpb.Download\x12/\n" +
	"\x06Upload\x12\x13.sudosocpb.UploadReq\x1a\x10.sudosocpb.Upload\x12)\n" +
	"\x04Grep\x12\x11.sudosocpb.GrepReq\x1a\x0e.sudosocpb.Grep\x12,\n" +
	"\x05Chmod\x12\x12.sudosocpb.ChmodReq\x1a\x0f.sudosocpb.Chmod\x12,\n" +
	"\x05Chown\x12\x12.sudosocpb.ChownReq\x1a\x0f.sudosocpb.Chown\x122\n" +
	"\aChtimes\x12\x14.sudosocpb.ChtimesReq\x1a\x11.sudosocpb.Chtimes\x127\n" +
	"\fMemfilesList\x12\x19.sudosocpb.MemfilesListReq\x1a\f.sudosocpb.Ls\x12>\n" +
	"\vMemfilesAdd\x12\x18.sudosocpb.MemfilesAddReq\x1a\x15.sudosocpb.MemfilesAdd\x12;\n" +
	"\n" +
	"MemfilesRm\x12\x17.sudosocpb.MemfilesRmReq\x1a\x14.sudosocpb.MemfilesRm\x12,\n" +
	"\x05Mount\x12\x12.sudosocpb.MountReq\x1a\x0f.sudosocpb.Mount\x12>\n" +
	"\vProcessDump\x12\x18.sudosocpb.ProcessDumpReq\x1a\x15.sudosocpb.ProcessDump\x12,\n" +
	"\x05RunAs\x12\x12.sudosocpb.RunAsReq\x1a\x0f.sudosocpb.RunAs\x12>\n" +
	"\vImpersonate\x12\x18.sudosocpb.ImpersonateReq\x1a\x15.sudosocpb.Impersonate\x128\n" +
	"\tRevToSelf\x12\x16.sudosocpb.RevToSelfReq\x1a\x13.sudosocpb.RevToSelf\x128\n" +
	"\tGetSystem\x12\x16.clientpb.GetSystemReq\x1a\x13.sudosocpb.GetSystem\x12)\n" +
	"\x04Task\x12\x11.sudosocpb.TaskReq\x1a\x0e.sudosocpb.Task\x12'\n" +
	"\x03Msf\x12\x10.clientpb.MSFReq\x1a\x0e.sudosocpb.Task\x123\n" +
	"\tMsfRemote\x12\x16.clientpb.MSFRemoteReq\x1a\x0e.sudosocpb.Task\x12J\n" +
	"\x0fExecuteAssembly\x12\x1c.sudosocpb.ExecuteAssemblyReq\x1a\x19.sudosocpb.ExecuteAssembly\x122\n" +
	"\aMigrate\x12\x14.clientpb.MigrateReq\x1a\x11.sudosocpb.Migrate\x122\n" +
	"\aExecute\x12\x14.sudosocpb.ExecuteReq\x1a\x11.sudosocpb.Execute\x12@\n" +
	"\x0eExecuteWindows\x12\x1b.sudosocpb.ExecuteWindowsReq\x1a\x11.sudosocpb.Execute\x12J\n" +
	"\x0fExecuteChildren\x12\x1c.sudosocpb.ExecuteChildrenReq\x1a\x19.sudosocpb.ExecuteChildren\x125\n" +
	"\bSideload\x12\x15.sudosocpb.SideloadReq\x1a\x12.sudosocpb.Sideload\x12;\n" +
	"\bSpawnDll\x12\x1b.sudosocpb.InvokeSpawnDllReq\x1a\x12.sudosocpb.SpawnDll\x12;\n" +
	"\n" +
	"Screenshot\x12\x17.sudosocpb.ScreenshotReq\x1a\x14.sudosocpb.Screenshot\x12P\n" +
	"\x11CurrentTokenOwner\x12\x1e.sudosocpb.CurrentTokenOwnerReq\x1a\x1b.sudosocpb.CurrentTokenOwner\x125\n" +
	"\bServices\x12\x15.sudosocpb.ServicesReq\x1a\x12.sudosocpb.Services\x12D\n" +
	"\rServiceDetail\x12\x1a.sudosocpb.ServiceDetailReq\x1a\x17.sudosocpb.ServiceDetail\x12L\n" +
	"\x12StartServiceByName\x12\x1f.sudosocpb.StartServiceByNameReq\x1a\x15.sudosocpb.ServiceInfo\x12N\n" +
	"\x12PivotStartListener\x12\x1f.sudosocpb.PivotStartListenerReq\x1a\x17.sudosocpb.PivotListener\x12D\n" +
	"\x11PivotStopListener\x12\x1e.sudosocpb.PivotStopListenerReq\x1a\x0f.commonpb.Empty\x12N\n" +
	"\x15PivotSessionListeners\x12\x1b.sudosocpb.PivotListenersReq\x1a\x18.sudosocpb.PivotListeners\x123\n" +
	"\n" +
	"PivotGraph\x12\x0f.commonpb.Empty\x1a\x14.clientpb.PivotGraph\x12@\n" +
	"\fStartService\x12\x19.sudosocpb.StartServiceReq\x1a\x15.sudosocpb.ServiceInfo\x12>\n" +
	"\vStopService\x12\x18.sudosocpb.StopServiceReq\x1a\x15.sudosocpb.ServiceInfo\x12B\n" +
	"\rRemoveService\x12\x1a.sudosocpb.RemoveServiceReq\x1a\x15.sudosocpb.ServiceInfo\x128\n" +
	"\tMakeToken\x12\x16.sudosocpb.MakeTokenReq\x1a\x13.sudosocpb.MakeToken\x12-\n" +
	"\x06GetEnv\x12\x10.sudosocpb.EnvReq\x1a\x11.sudosocpb.EnvInfo\x12/\n" +
	"\x06SetEnv\x12\x13.sudosocpb.SetEnvReq\x1a\x10.sudosocpb.SetEnv\x125\n" +
	"\bUnsetEnv\x12\x15.sudosocpb.UnsetEnvReq\x1a\x12.sudosocpb.UnsetEnv\x125\n" +
	"\bBackdoor\x12\x15.clientpb.BackdoorReq\x1a\x12.clientpb.Backdoor\x12A\n" +
	"\fRegistryRead\x12\x19.sudosocpb.RegistryReadReq\x1a\x16.sudosocpb.RegistryRead\x12D\n" +
	"\rRegistryWrite\x12\x1a.sudosocpb.RegistryWriteReq\x1a\x17.sudosocpb.RegistryWrite\x12P\n" +
	"\x11RegistryCreateKey\x12\x1e.sudosocpb.RegistryCreateKeyReq\x1a\x1b.sudosocpb.RegistryCreateKey\x12P\n" +
	"\x11RegistryDeleteKey\x12\x1e.sudosocpb.RegistryDeleteKeyReq\x1a\x1b.sudosocpb.RegistryDeleteKey\x12T\n" +
	"\x13RegistryListSubKeys\x12\x1f.sudosocpb.RegistrySubKeyListReq\x1a\x1c.sudosocpb.RegistrySubKeyList\x12S\n" +
	"\x12RegistryListValues\x12\x1f.sudosocpb.RegistryListValuesReq\x1a\x1c.sudosocpb.RegistryValuesList\x12M\n" +
	"\x10RegistryReadHive\x12\x1d.sudosocpb.RegistryReadHiveReq\x1a\x1a.sudosocpb.RegistryReadHive\x12>\n" +
	"\rRunSSHCommand\x12\x17.sudosocpb.SSHCommandReq\x1a\x14.sudosocpb.SSHCommand\x128\n" +
	"\tHijackDLL\x12\x16.clientpb.DllHijackReq\x1a\x13.clientpb.DllHijack\x125\n" +
	"\bGetPrivs\x12\x15.sudosocpb.GetPrivsReq\x1a\x12.sudosocpb.GetPrivs\x12W\n" +
	"\x15StartRportFwdListener\x12\".sudosocpb.RportFwdStartListenerReq\x1a\x1a.sudosocpb.RportFwdListener\x12S\n" +
	"\x14GetRportFwdListeners\x12\x1e.sudosocpb.RportFwdListenersReq\x1a\x1b.sudosocpb.RportFwdListeners\x12U\n" +
	"\x14StopRportFwdListener\x12!.sudosocpb.RportFwdStopListenerReq\x1a\x1a.sudosocpb.RportFwdListener\x12;\n" +
	"\vOpenSession\x12\x15.sudosocpb.OpenSession\x1a\x15.sudosocpb.OpenSession\x127\n" +
	"\fCloseSession\x12\x16.sudosocpb.CloseSession\x1a\x0f.commonpb.Empty\x12P\n" +
	"\x11RegisterExtension\x12\x1e.sudosocpb.RegisterExtensionReq\x1a\x1b.sudosocpb.RegisterExtension\x12D\n" +
	"\rCallExtension\x12\x1a.sudosocpb.CallExtensionReq\x1a\x17.sudosocpb.CallExtension\x12G\n" +
	"\x0eListExtensions\x12\x1b.sudosocpb.ListExtensionsReq\x1a\x18.sudosocpb.ListExtensions\x12\\\n" +
	"\x15RegisterWasmExtension\x12\".sudosocpb.RegisterWasmExtensionReq\x1a\x1f.sudosocpb.RegisterWasmExtension\x12S\n" +
	"\x12ListWasmExtensions\x12\x1f.sudosocpb.ListWasmExtensionsReq\x1a\x1c.sudosocpb.ListWasmExtensions\x12P\n" +
	"\x11ExecWasmExtension\x12\x1e.sudosocpb.ExecWasmExtensionReq\x1a\x1b.sudosocpb.ExecWasmExtension\x12N\n" +
	"\x12WGStartPortForward\x12\x1f.sudosocpb.WGPortForwardStartReq\x1a\x17.sudosocpb.WGPortForward\x12L\n" +
	"\x11WGStopPortForward\x12\x1e.sudosocpb.WGPortForwardStopReq\x1a\x17.sudosocpb.WGPortForward\x12<\n" +
	"\fWGStartSocks\x12\x19.sudosocpb.WGSocksStartReq\x1a\x11.sudosocpb.WGSocks\x12:\n" +
	"\vWGStopSocks\x12\x18.sudosocpb.WGSocksStopReq\x1a\x11.sudosocpb.WGSocks\x12K\n" +
	"\x10WGListForwarders\x12\x1c.sudosocpb.WGTCPForwardersReq\x1a\x19.sudosocpb.WGTCPForwarders\x12K\n" +
	"\x12WGListSocksServers\x12\x1b.sudosocpb.WGSocksServersReq\x1a\x18.sudosocpb.WGSocksServers\x12,\n" +
	"\x05Shell\x12\x12.sudosocpb.ShellReq\x1a\x0f.sudosocpb.Shell\x128\n" +
	"\vShellResize\x12\x18.sudosocpb.ShellResizeReq\x1a\x0f.commonpb.Empty\x122\n" +
	"\aPortfwd\x12\x14.sudosocpb.PortfwdReq\x1a\x11.sudosocpb.Portfwd\x12/\n" +
	"\vCreateSocks\x12\x0f.sudosocpb.Socks\x1a\x0f.sudosocpb.Socks\x12.\n" +
	"\n" +
	"CloseSocks\x12\x0f.sudosocpb.Socks\x1a\x0f.commonpb.Empty\x12:\n" +
	"\n" +
	"SocksProxy\x12\x13.sudosocpb.SocksData\x1a\x13.sudosocpb.SocksData(\x010\x01\x122\n" +
	"\fCreateTunnel\x12\x10.sudosocpb.Tunnel\x1a\x10.sudosocpb.Tunnel\x120\n" +
	"\vCloseTunnel\x12\x10.sudosocpb.Tunnel\x1a\x0f.commonpb.Empty\x12<\n" +
	"\n" +
	"TunnelData\x12\x14.sudosocpb.TunnelData\x1a\x14.sudosocpb.TunnelData(\x010\x01\x12,\n" +
	"\x06Events\x12\x0f.commonpb.Empty\x1a\x0f.clientpb.Event0\x01B,Z*github.com/sudosoc/SUDOSOC-C2/protobuf/rpcpbb\x06proto3"

var file_rpcpb_services_proto_goTypes = []any{
	(*commonpb.Empty)(nil),                    // 0: commonpb.Empty
	(*clientpb.ClientLogData)(nil),            // 1: clientpb.ClientLogData
	(*sudosocpb.KillReq)(nil),                  // 2: sudosocpb.KillReq
	(*sudosocpb.ReconfigureReq)(nil),           // 3: sudosocpb.ReconfigureReq
	(*clientpb.RenameReq)(nil),                // 4: clientpb.RenameReq
	(*clientpb.MonitoringProvider)(nil),       // 5: clientpb.MonitoringProvider
	(*clientpb.AIConversationReq)(nil),        // 6: clientpb.AIConversationReq
	(*clientpb.AIConversation)(nil),           // 7: clientpb.AIConversation
	(*clientpb.AIConversationMessage)(nil),    // 8: clientpb.AIConversationMessage
	(*clientpb.MTLSListenerReq)(nil),          // 9: clientpb.MTLSListenerReq
	(*clientpb.WGListenerReq)(nil),            // 10: clientpb.WGListenerReq
	(*clientpb.DNSListenerReq)(nil),           // 11: clientpb.DNSListenerReq
	(*clientpb.HTTPListenerReq)(nil),          // 12: clientpb.HTTPListenerReq
	(*clientpb.Beacon)(nil),                   // 13: clientpb.Beacon
	(*clientpb.BeaconTask)(nil),               // 14: clientpb.BeaconTask
	(*clientpb.BeaconIntegrity)(nil),          // 15: clientpb.BeaconIntegrity
	(*clientpb.KillJobReq)(nil),               // 16: clientpb.KillJobReq
	(*clientpb.RestartJobReq)(nil),            // 17: clientpb.RestartJobReq
	(*clientpb.StagerListenerReq)(nil),        // 18: clientpb.StagerListenerReq
	(*clientpb.Loot)(nil),                     // 19: clientpb.Loot
	(*clientpb.Credentials)(nil),              // 20: clientpb.Credentials
	(*clientpb.Credential)(nil),               // 21: clientpb.Credential
	(*clientpb.Host)(nil),                     // 22: clientpb.Host
	(*clientpb.IOC)(nil),                      // 23: clientpb.IOC
	(*clientpb.GenerateReq)(nil),              // 24: clientpb.GenerateReq
	(*clientpb.GenerateSpoofMetadataReq)(nil), // 25: clientpb.GenerateSpoofMetadataReq
	(*clientpb.ExternalGenerateReq)(nil),      // 26: clientpb.ExternalGenerateReq
	(*clientpb.ExternalImplantBinary)(nil),    // 27: clientpb.ExternalImplantBinary
	(*clientpb.ImplantBuild)(nil),             // 28: clientpb.ImplantBuild
	(*clientpb.GenerateStageReq)(nil),         // 29: clientpb.GenerateStageReq
	(*clientpb.ImplantStageReq)(nil),          // 30: clientpb.ImplantStageReq
	(*clientpb.C2ProfileReq)(nil),             // 31: clientpb.C2ProfileReq
	(*clientpb.HTTPC2ConfigReq)(nil),          // 32: clientpb.HTTPC2ConfigReq
	(*clientpb.Builder)(nil),                  // 33: clientpb.Builder
	(*clientpb.Event)(nil),                    // 34: clientpb.Event
	(*clientpb.CertificatesReq)(nil),          // 35: clientpb.CertificatesReq
	(*clientpb.CrackCommand)(nil),             // 36: clientpb.CrackCommand
	(*clientpb.Crackstation)(nil),             // 37: clientpb.Crackstation
	(*clientpb.CrackBenchmark)(nil),           // 38: clientpb.CrackBenchmark
	(*clientpb.CrackTask)(nil),                // 39: clientpb.CrackTask
	(*clientpb.CrackFile)(nil),                // 40: clientpb.CrackFile
	(*clientpb.CrackFileChunk)(nil),           // 41: clientpb.CrackFileChunk
	(*clientpb.RegenerateReq)(nil),            // 42: clientpb.RegenerateReq
	(*clientpb.DeleteReq)(nil),                // 43: clientpb.DeleteReq
	(*clientpb.ImplantProfile)(nil),           // 44: clientpb.ImplantProfile
	(*clientpb.ShellcodeRDIReq)(nil),          // 45: clientpb.ShellcodeRDIReq
	(*clientpb.ShellcodeEncodeReq)(nil),       // 46: clientpb.ShellcodeEncodeReq
	(*clientpb.TrafficEncoder)(nil),           // 47: clientpb.TrafficEncoder
	(*clientpb.Website)(nil),                  // 48: clientpb.Website
	(*clientpb.WebsiteAddContent)(nil),        // 49: clientpb.WebsiteAddContent
	(*clientpb.WebsiteRemoveContent)(nil),     // 50: clientpb.WebsiteRemoveContent
	(*sudosocpb.Ping)(nil),                     // 51: sudosocpb.Ping
	(*sudosocpb.PsReq)(nil),                    // 52: sudosocpb.PsReq
	(*sudosocpb.TerminateReq)(nil),             // 53: sudosocpb.TerminateReq
	(*sudosocpb.IfconfigReq)(nil),              // 54: sudosocpb.IfconfigReq
	(*sudosocpb.NetstatReq)(nil),               // 55: sudosocpb.NetstatReq
	(*sudosocpb.LsReq)(nil),                    // 56: sudosocpb.LsReq
	(*sudosocpb.CdReq)(nil),                    // 57: sudosocpb.CdReq
	(*sudosocpb.PwdReq)(nil),                   // 58: sudosocpb.PwdReq
	(*sudosocpb.MvReq)(nil),                    // 59: sudosocpb.MvReq
	(*sudosocpb.CpReq)(nil),                    // 60: sudosocpb.CpReq
	(*sudosocpb.RmReq)(nil),                    // 61: sudosocpb.RmReq
	(*sudosocpb.MkdirReq)(nil),                 // 62: sudosocpb.MkdirReq
	(*sudosocpb.DownloadReq)(nil),              // 63: sudosocpb.DownloadReq
	(*sudosocpb.UploadReq)(nil),                // 64: sudosocpb.UploadReq
	(*sudosocpb.GrepReq)(nil),                  // 65: sudosocpb.GrepReq
	(*sudosocpb.ChmodReq)(nil),                 // 66: sudosocpb.ChmodReq
	(*sudosocpb.ChownReq)(nil),                 // 67: sudosocpb.ChownReq
	(*sudosocpb.ChtimesReq)(nil),               // 68: sudosocpb.ChtimesReq
	(*sudosocpb.MemfilesListReq)(nil),          // 69: sudosocpb.MemfilesListReq
	(*sudosocpb.MemfilesAddReq)(nil),           // 70: sudosocpb.MemfilesAddReq
	(*sudosocpb.MemfilesRmReq)(nil),            // 71: sudosocpb.MemfilesRmReq
	(*sudosocpb.MountReq)(nil),                 // 72: sudosocpb.MountReq
	(*sudosocpb.ProcessDumpReq)(nil),           // 73: sudosocpb.ProcessDumpReq
	(*sudosocpb.RunAsReq)(nil),                 // 74: sudosocpb.RunAsReq
	(*sudosocpb.ImpersonateReq)(nil),           // 75: sudosocpb.ImpersonateReq
	(*sudosocpb.RevToSelfReq)(nil),             // 76: sudosocpb.RevToSelfReq
	(*clientpb.GetSystemReq)(nil),             // 77: clientpb.GetSystemReq
	(*sudosocpb.TaskReq)(nil),                  // 78: sudosocpb.TaskReq
	(*clientpb.MSFReq)(nil),                   // 79: clientpb.MSFReq
	(*clientpb.MSFRemoteReq)(nil),             // 80: clientpb.MSFRemoteReq
	(*sudosocpb.ExecuteAssemblyReq)(nil),       // 81: sudosocpb.ExecuteAssemblyReq
	(*clientpb.MigrateReq)(nil),               // 82: clientpb.MigrateReq
	(*sudosocpb.ExecuteReq)(nil),               // 83: sudosocpb.ExecuteReq
	(*sudosocpb.ExecuteWindowsReq)(nil),        // 84: sudosocpb.ExecuteWindowsReq
	(*sudosocpb.ExecuteChildrenReq)(nil),       // 85: sudosocpb.ExecuteChildrenReq
	(*sudosocpb.SideloadReq)(nil),              // 86: sudosocpb.SideloadReq
	(*sudosocpb.InvokeSpawnDllReq)(nil),        // 87: sudosocpb.InvokeSpawnDllReq
	(*sudosocpb.ScreenshotReq)(nil),            // 88: sudosocpb.ScreenshotReq
	(*sudosocpb.CurrentTokenOwnerReq)(nil),     // 89: sudosocpb.CurrentTokenOwnerReq
	(*sudosocpb.ServicesReq)(nil),              // 90: sudosocpb.ServicesReq
	(*sudosocpb.ServiceDetailReq)(nil),         // 91: sudosocpb.ServiceDetailReq
	(*sudosocpb.StartServiceByNameReq)(nil),    // 92: sudosocpb.StartServiceByNameReq
	(*sudosocpb.PivotStartListenerReq)(nil),    // 93: sudosocpb.PivotStartListenerReq
	(*sudosocpb.PivotStopListenerReq)(nil),     // 94: sudosocpb.PivotStopListenerReq
	(*sudosocpb.PivotListenersReq)(nil),        // 95: sudosocpb.PivotListenersReq
	(*sudosocpb.StartServiceReq)(nil),          // 96: sudosocpb.StartServiceReq
	(*sudosocpb.StopServiceReq)(nil),           // 97: sudosocpb.StopServiceReq
	(*sudosocpb.RemoveServiceReq)(nil),         // 98: sudosocpb.RemoveServiceReq
	(*sudosocpb.MakeTokenReq)(nil),             // 99: sudosocpb.MakeTokenReq
	(*sudosocpb.EnvReq)(nil),                   // 100: sudosocpb.EnvReq
	(*sudosocpb.SetEnvReq)(nil),                // 101: sudosocpb.SetEnvReq
	(*sudosocpb.UnsetEnvReq)(nil),              // 102: sudosocpb.UnsetEnvReq
	(*clientpb.BackdoorReq)(nil),              // 103: clientpb.BackdoorReq
	(*sudosocpb.RegistryReadReq)(nil),          // 104: sudosocpb.RegistryReadReq
	(*sudosocpb.RegistryWriteReq)(nil),         // 105: sudosocpb.RegistryWriteReq
	(*sudosocpb.RegistryCreateKeyReq)(nil),     // 106: sudosocpb.RegistryCreateKeyReq
	(*sudosocpb.RegistryDeleteKeyReq)(nil),     // 107: sudosocpb.RegistryDeleteKeyReq
	(*sudosocpb.RegistrySubKeyListReq)(nil),    // 108: sudosocpb.RegistrySubKeyListReq
	(*sudosocpb.RegistryListValuesReq)(nil),    // 109: sudosocpb.RegistryListValuesReq
	(*sudosocpb.RegistryReadHiveReq)(nil),      // 110: sudosocpb.RegistryReadHiveReq
	(*sudosocpb.SSHCommandReq)(nil),            // 111: sudosocpb.SSHCommandReq
	(*clientpb.DllHijackReq)(nil),             // 112: clientpb.DllHijackReq
	(*sudosocpb.GetPrivsReq)(nil),              // 113: sudosocpb.GetPrivsReq
	(*sudosocpb.RportFwdStartListenerReq)(nil), // 114: sudosocpb.RportFwdStartListenerReq
	(*sudosocpb.RportFwdListenersReq)(nil),     // 115: sudosocpb.RportFwdListenersReq
	(*sudosocpb.RportFwdStopListenerReq)(nil),  // 116: sudosocpb.RportFwdStopListenerReq
	(*sudosocpb.OpenSession)(nil),              // 117: sudosocpb.OpenSession
	(*sudosocpb.CloseSession)(nil),             // 118: sudosocpb.CloseSession
	(*sudosocpb.RegisterExtensionReq)(nil),     // 119: sudosocpb.RegisterExtensionReq
	(*sudosocpb.CallExtensionReq)(nil),         // 120: sudosocpb.CallExtensionReq
	(*sudosocpb.ListExtensionsReq)(nil),        // 121: sudosocpb.ListExtensionsReq
	(*sudosocpb.RegisterWasmExtensionReq)(nil), // 122: sudosocpb.RegisterWasmExtensionReq
	(*sudosocpb.ListWasmExtensionsReq)(nil),    // 123: sudosocpb.ListWasmExtensionsReq
	(*sudosocpb.ExecWasmExtensionReq)(nil),     // 124: sudosocpb.ExecWasmExtensionReq
	(*sudosocpb.WGPortForwardStartReq)(nil),    // 125: sudosocpb.WGPortForwardStartReq
	(*sudosocpb.WGPortForwardStopReq)(nil),     // 126: sudosocpb.WGPortForwardStopReq
	(*sudosocpb.WGSocksStartReq)(nil),          // 127: sudosocpb.WGSocksStartReq
	(*sudosocpb.WGSocksStopReq)(nil),           // 128: sudosocpb.WGSocksStopReq
	(*sudosocpb.WGTCPForwardersReq)(nil),       // 129: sudosocpb.WGTCPForwardersReq
	(*sudosocpb.WGSocksServersReq)(nil),        // 130: sudosocpb.WGSocksServersReq
	(*sudosocpb.ShellReq)(nil),                 // 131: sudosocpb.ShellReq
	(*sudosocpb.ShellResizeReq)(nil),           // 132: sudosocpb.ShellResizeReq
	(*sudosocpb.PortfwdReq)(nil),               // 133: sudosocpb.PortfwdReq
	(*sudosocpb.Socks)(nil),                    // 134: sudosocpb.Socks
	(*sudosocpb.SocksData)(nil),                // 135: sudosocpb.SocksData
	(*sudosocpb.Tunnel)(nil),                   // 136: sudosocpb.Tunnel
	(*sudosocpb.TunnelData)(nil),               // 137: sudosocpb.TunnelData
	(*clientpb.Version)(nil),                  // 138: clientpb.Version
	(*clientpb.Operators)(nil),                // 139: clientpb.Operators
	(*sudosocpb.Reconfigure)(nil),              // 140: sudosocpb.Reconfigure
	(*clientpb.Sessions)(nil),                 // 141: clientpb.Sessions
	(*commonpb.Response)(nil),                 // 142: commonpb.Response
	(*clientpb.MonitoringProviders)(nil),      // 143: clientpb.MonitoringProviders
	(*clientpb.AIProviderConfigs)(nil),        // 144: clientpb.AIProviderConfigs
	(*clientpb.AIConversations)(nil),          // 145: clientpb.AIConversations
	(*clientpb.AIConversationMessages)(nil),   // 146: clientpb.AIConversationMessages
	(*clientpb.ListenerJob)(nil),              // 147: clientpb.ListenerJob
	(*clientpb.Beacons)(nil),                  // 148: clientpb.Beacons
	(*clientpb.BeaconTasks)(nil),              // 149: clientpb.BeaconTasks
	(*clientpb.Jobs)(nil),                     // 150: clientpb.Jobs
	(*clientpb.KillJob)(nil),                  // 151: clientpb.KillJob
	(*clientpb.StagerListener)(nil),           // 152: clientpb.StagerListener
	(*clientpb.AllLoot)(nil),                  // 153: clientpb.AllLoot
	(*clientpb.AllHosts)(nil),                 // 154: clientpb.AllHosts
	(*clientpb.Generate)(nil),                 // 155: clientpb.Generate
	(*clientpb.ExternalImplantConfig)(nil),    // 156: clientpb.ExternalImplantConfig
	(*clientpb.HTTPC2Configs)(nil),            // 157: clientpb.HTTPC2Configs
	(*clientpb.HTTPC2Config)(nil),             // 158: clientpb.HTTPC2Config
	(*clientpb.Builders)(nil),                 // 159: clientpb.Builders
	(*clientpb.CertificateInfo)(nil),          // 160: clientpb.CertificateInfo
	(*clientpb.CertificateAuthorityInfo)(nil), // 161: clientpb.CertificateAuthorityInfo
	(*clientpb.CrackResponse)(nil),            // 162: clientpb.CrackResponse
	(*clientpb.Crackstations)(nil),            // 163: clientpb.Crackstations
	(*clientpb.CrackFiles)(nil),               // 164: clientpb.CrackFiles
	(*clientpb.ImplantBuilds)(nil),            // 165: clientpb.ImplantBuilds
	(*clientpb.Canaries)(nil),                 // 166: clientpb.Canaries
	(*clientpb.WGClientConfig)(nil),           // 167: clientpb.WGClientConfig
	(*clientpb.UniqueWGIP)(nil),               // 168: clientpb.UniqueWGIP
	(*clientpb.ImplantProfiles)(nil),          // 169: clientpb.ImplantProfiles
	(*clientpb.ShellcodeRDI)(nil),             // 170: clientpb.ShellcodeRDI
	(*clientpb.Compiler)(nil),                 // 171: clientpb.Compiler
	(*clientpb.ShellcodeEncode)(nil),          // 172: clientpb.ShellcodeEncode
	(*clientpb.ShellcodeEncoderMap)(nil),      // 173: clientpb.ShellcodeEncoderMap
	(*clientpb.TrafficEncoderMap)(nil),        // 174: clientpb.TrafficEncoderMap
	(*clientpb.TrafficEncoderTests)(nil),      // 175: clientpb.TrafficEncoderTests
	(*clientpb.Websites)(nil),                 // 176: clientpb.Websites
	(*sudosocpb.Ps)(nil),                       // 177: sudosocpb.Ps
	(*sudosocpb.Terminate)(nil),                // 178: sudosocpb.Terminate
	(*sudosocpb.Ifconfig)(nil),                 // 179: sudosocpb.Ifconfig
	(*sudosocpb.Netstat)(nil),                  // 180: sudosocpb.Netstat
	(*sudosocpb.Ls)(nil),                       // 181: sudosocpb.Ls
	(*sudosocpb.Pwd)(nil),                      // 182: sudosocpb.Pwd
	(*sudosocpb.Mv)(nil),                       // 183: sudosocpb.Mv
	(*sudosocpb.Cp)(nil),                       // 184: sudosocpb.Cp
	(*sudosocpb.Rm)(nil),                       // 185: sudosocpb.Rm
	(*sudosocpb.Mkdir)(nil),                    // 186: sudosocpb.Mkdir
	(*sudosocpb.Download)(nil),                 // 187: sudosocpb.Download
	(*sudosocpb.Upload)(nil),                   // 188: sudosocpb.Upload
	(*sudosocpb.Grep)(nil),                     // 189: sudosocpb.Grep
	(*sudosocpb.Chmod)(nil),                    // 190: sudosocpb.Chmod
	(*sudosocpb.Chown)(nil),                    // 191: sudosocpb.Chown
	(*sudosocpb.Chtimes)(nil),                  // 192: sudosocpb.Chtimes
	(*sudosocpb.MemfilesAdd)(nil),              // 193: sudosocpb.MemfilesAdd
	(*sudosocpb.MemfilesRm)(nil),               // 194: sudosocpb.MemfilesRm
	(*sudosocpb.Mount)(nil),                    // 195: sudosocpb.Mount
	(*sudosocpb.ProcessDump)(nil),              // 196: sudosocpb.ProcessDump
	(*sudosocpb.RunAs)(nil),                    // 197: sudosocpb.RunAs
	(*sudosocpb.Impersonate)(nil),              // 198: sudosocpb.Impersonate
	(*sudosocpb.RevToSelf)(nil),                // 199: sudosocpb.RevToSelf
	(*sudosocpb.GetSystem)(nil),                // 200: sudosocpb.GetSystem
	(*sudosocpb.Task)(nil),                     // 201: sudosocpb.Task
	(*sudosocpb.ExecuteAssembly)(nil),          // 202: sudosocpb.ExecuteAssembly
	(*sudosocpb.Migrate)(nil),                  // 203: sudosocpb.Migrate
	(*sudosocpb.Execute)(nil),                  // 204: sudosocpb.Execute
	(*sudosocpb.ExecuteChildren)(nil),          // 205: sudosocpb.ExecuteChildren
	(*sudosocpb.Sideload)(nil),                 // 206: sudosocpb.Sideload
	(*sudosocpb.SpawnDll)(nil),                 // 207: sudosocpb.SpawnDll
	(*sudosocpb.Screenshot)(nil),               // 208: sudosocpb.Screenshot
	(*sudosocpb.CurrentTokenOwner)(nil),        // 209: sudosocpb.CurrentTokenOwner
	(*sudosocpb.Services)(nil),                 // 210: sudosocpb.Services
	(*sudosocpb.ServiceDetail)(nil),            // 211: sudosocpb.ServiceDetail
	(*sudosocpb.ServiceInfo)(nil),              // 212: sudosocpb.ServiceInfo
	(*sudosocpb.PivotListener)(nil),            // 213: sudosocpb.PivotListener
	(*sudosocpb.PivotListeners)(nil),           // 214: sudosocpb.PivotListeners
	(*clientpb.PivotGraph)(nil),               // 215: clientpb.PivotGraph
	(*sudosocpb.MakeToken)(nil),                // 216: sudosocpb.MakeToken
	(*sudosocpb.EnvInfo)(nil),                  // 217: sudosocpb.EnvInfo
	(*sudosocpb.SetEnv)(nil),                   // 218: sudosocpb.SetEnv
	(*sudosocpb.UnsetEnv)(nil),                 // 219: sudosocpb.UnsetEnv
	(*clientpb.Backdoor)(nil),                 // 220: clientpb.Backdoor
	(*sudosocpb.RegistryRead)(nil),             // 221: sudosocpb.RegistryRead
	(*sudosocpb.RegistryWrite)(nil),            // 222: sudosocpb.RegistryWrite
	(*sudosocpb.RegistryCreateKey)(nil),        // 223: sudosocpb.RegistryCreateKey
	(*sudosocpb.RegistryDeleteKey)(nil),        // 224: sudosocpb.RegistryDeleteKey
	(*sudosocpb.RegistrySubKeyList)(nil),       // 225: sudosocpb.RegistrySubKeyList
	(*sudosocpb.RegistryValuesList)(nil),       // 226: sudosocpb.RegistryValuesList
	(*sudosocpb.RegistryReadHive)(nil),         // 227: sudosocpb.RegistryReadHive
	(*sudosocpb.SSHCommand)(nil),               // 228: sudosocpb.SSHCommand
	(*clientpb.DllHijack)(nil),                // 229: clientpb.DllHijack
	(*sudosocpb.GetPrivs)(nil),                 // 230: sudosocpb.GetPrivs
	(*sudosocpb.RportFwdListener)(nil),         // 231: sudosocpb.RportFwdListener
	(*sudosocpb.RportFwdListeners)(nil),        // 232: sudosocpb.RportFwdListeners
	(*sudosocpb.RegisterExtension)(nil),        // 233: sudosocpb.RegisterExtension
	(*sudosocpb.CallExtension)(nil),            // 234: sudosocpb.CallExtension
	(*sudosocpb.ListExtensions)(nil),           // 235: sudosocpb.ListExtensions
	(*sudosocpb.RegisterWasmExtension)(nil),    // 236: sudosocpb.RegisterWasmExtension
	(*sudosocpb.ListWasmExtensions)(nil),       // 237: sudosocpb.ListWasmExtensions
	(*sudosocpb.ExecWasmExtension)(nil),        // 238: sudosocpb.ExecWasmExtension
	(*sudosocpb.WGPortForward)(nil),            // 239: sudosocpb.WGPortForward
	(*sudosocpb.WGSocks)(nil),                  // 240: sudosocpb.WGSocks
	(*sudosocpb.WGTCPForwarders)(nil),          // 241: sudosocpb.WGTCPForwarders
	(*sudosocpb.WGSocksServers)(nil),           // 242: sudosocpb.WGSocksServers
	(*sudosocpb.Shell)(nil),                    // 243: sudosocpb.Shell
	(*sudosocpb.Portfwd)(nil),                  // 244: sudosocpb.Portfwd
}
var file_rpcpb_services_proto_depIdxs = []int32{
	0,   // 0: rpcpb.CoreRPC.GetVersion:input_type -> commonpb.Empty
	1,   // 1: rpcpb.CoreRPC.ClientLog:input_type -> clientpb.ClientLogData
	0,   // 2: rpcpb.CoreRPC.GetOperators:input_type -> commonpb.Empty
	2,   // 3: rpcpb.CoreRPC.Kill:input_type -> sudosocpb.KillReq
	3,   // 4: rpcpb.CoreRPC.Reconfigure:input_type -> sudosocpb.ReconfigureReq
	4,   // 5: rpcpb.CoreRPC.Rename:input_type -> clientpb.RenameReq
	0,   // 6: rpcpb.CoreRPC.GetSessions:input_type -> commonpb.Empty
	0,   // 7: rpcpb.CoreRPC.MonitorStart:input_type -> commonpb.Empty
	0,   // 8: rpcpb.CoreRPC.MonitorStop:input_type -> commonpb.Empty
	0,   // 9: rpcpb.CoreRPC.MonitorListConfig:input_type -> commonpb.Empty
	5,   // 10: rpcpb.CoreRPC.MonitorAddConfig:input_type -> clientpb.MonitoringProvider
	5,   // 11: rpcpb.CoreRPC.MonitorDelConfig:input_type -> clientpb.MonitoringProvider
	0,   // 12: rpcpb.CoreRPC.GetAIProviders:input_type -> commonpb.Empty
	0,   // 13: rpcpb.CoreRPC.GetAIConversations:input_type -> commonpb.Empty
	6,   // 14: rpcpb.CoreRPC.GetAIConversation:input_type -> clientpb.AIConversationReq
	7,   // 15: rpcpb.CoreRPC.SaveAIConversation:input_type -> clientpb.AIConversation
	6,   // 16: rpcpb.CoreRPC.DeleteAIConversation:input_type -> clientpb.AIConversationReq
	6,   // 17: rpcpb.CoreRPC.GetAIConversationMessages:input_type -> clientpb.AIConversationReq
	8,   // 18: rpcpb.CoreRPC.SaveAIConversationMessage:input_type -> clientpb.AIConversationMessage
	9,   // 19: rpcpb.CoreRPC.StartMTLSListener:input_type -> clientpb.MTLSListenerReq
	10,  // 20: rpcpb.CoreRPC.StartWGListener:input_type -> clientpb.WGListenerReq
	11,  // 21: rpcpb.CoreRPC.StartDNSListener:input_type -> clientpb.DNSListenerReq
	12,  // 22: rpcpb.CoreRPC.StartHTTPSListener:input_type -> clientpb.HTTPListenerReq
	12,  // 23: rpcpb.CoreRPC.StartHTTPListener:input_type -> clientpb.HTTPListenerReq
	0,   // 24: rpcpb.CoreRPC.GetBeacons:input_type -> commonpb.Empty
	13,  // 25: rpcpb.CoreRPC.GetBeacon:input_type -> clientpb.Beacon
	13,  // 26: rpcpb.CoreRPC.RmBeacon:input_type -> clientpb.Beacon
	13,  // 27: rpcpb.CoreRPC.GetBeaconTasks:input_type -> clientpb.Beacon
	14,  // 28: rpcpb.CoreRPC.GetBeaconTaskContent:input_type -> clientpb.BeaconTask
	14,  // 29: rpcpb.CoreRPC.CancelBeaconTask:input_type -> clientpb.BeaconTask
	15,  // 30: rpcpb.CoreRPC.UpdateBeaconIntegrityInformation:input_type -> clientpb.BeaconIntegrity
	0,   // 31: rpcpb.CoreRPC.GetJobs:input_type -> commonpb.Empty
	16,  // 32: rpcpb.CoreRPC.KillJob:input_type -> clientpb.KillJobReq
	17,  // 33: rpcpb.CoreRPC.RestartJobs:input_type -> clientpb.RestartJobReq
	18,  // 34: rpcpb.CoreRPC.StartTCPStagerListener:input_type -> clientpb.StagerListenerReq
	19,  // 35: rpcpb.CoreRPC.LootAdd:input_type -> clientpb.Loot
	19,  // 36: rpcpb.CoreRPC.LootRm:input_type -> clientpb.Loot
	19,  // 37: rpcpb.CoreRPC.LootUpdate:input_type -> clientpb.Loot
	19,  // 38: rpcpb.CoreRPC.LootContent:input_type -> clientpb.Loot
	0,   // 39: rpcpb.CoreRPC.LootAll:input_type -> commonpb.Empty
	0,   // 40: rpcpb.CoreRPC.Creds:input_type -> commonpb.Empty
	20,  // 41: rpcpb.CoreRPC.CredsAdd:input_type -> clientpb.Credentials
	20,  // 42: rpcpb.CoreRPC.CredsRm:input_type -> clientpb.Credentials
	20,  // 43: rpcpb.CoreRPC.CredsUpdate:input_type -> clientpb.Credentials
	21,  // 44: rpcpb.CoreRPC.GetCredByID:input_type -> clientpb.Credential
	21,  // 45: rpcpb.CoreRPC.GetCredsByHashType:input_type -> clientpb.Credential
	21,  // 46: rpcpb.CoreRPC.GetPlaintextCredsByHashType:input_type -> clientpb.Credential
	21,  // 47: rpcpb.CoreRPC.CredsSniffHashType:input_type -> clientpb.Credential
	0,   // 48: rpcpb.CoreRPC.Hosts:input_type -> commonpb.Empty
	22,  // 49: rpcpb.CoreRPC.Host:input_type -> clientpb.Host
	22,  // 50: rpcpb.CoreRPC.HostRm:input_type -> clientpb.Host
	23,  // 51: rpcpb.CoreRPC.HostIOCRm:input_type -> clientpb.IOC
	24,  // 52: rpcpb.CoreRPC.Generate:input_type -> clientpb.GenerateReq
	25,  // 53: rpcpb.CoreRPC.GenerateSpoofMetadata:input_type -> clientpb.GenerateSpoofMetadataReq
	26,  // 54: rpcpb.CoreRPC.GenerateExternal:input_type -> clientpb.ExternalGenerateReq
	27,  // 55: rpcpb.CoreRPC.GenerateExternalSaveBuild:input_type -> clientpb.ExternalImplantBinary
	28,  // 56: rpcpb.CoreRPC.GenerateExternalGetBuildConfig:input_type -> clientpb.ImplantBuild
	29,  // 57: rpcpb.CoreRPC.GenerateStage:input_type -> clientpb.GenerateStageReq
	30,  // 58: rpcpb.CoreRPC.StageImplantBuild:input_type -> clientpb.ImplantStageReq
	0,   // 59: rpcpb.CoreRPC.GetHTTPC2Profiles:input_type -> commonpb.Empty
	31,  // 60: rpcpb.CoreRPC.GetHTTPC2ProfileByName:input_type -> clientpb.C2ProfileReq
	32,  // 61: rpcpb.CoreRPC.SaveHTTPC2Profile:input_type -> clientpb.HTTPC2ConfigReq
	33,  // 62: rpcpb.CoreRPC.BuilderRegister:input_type -> clientpb.Builder
	34,  // 63: rpcpb.CoreRPC.BuilderTrigger:input_type -> clientpb.Event
	0,   // 64: rpcpb.CoreRPC.Builders:input_type -> commonpb.Empty
	35,  // 65: rpcpb.CoreRPC.GetCertificateInfo:input_type -> clientpb.CertificatesReq
	0,   // 66: rpcpb.CoreRPC.GetCertificateAuthorityInfo:input_type -> commonpb.Empty
	36,  // 67: rpcpb.CoreRPC.Crack:input_type -> clientpb.CrackCommand
	37,  // 68: rpcpb.CoreRPC.CrackstationRegister:input_type -> clientpb.Crackstation
	34,  // 69: rpcpb.CoreRPC.CrackstationTrigger:input_type -> clientpb.Event
	38,  // 70: rpcpb.CoreRPC.CrackstationBenchmark:input_type -> clientpb.CrackBenchmark
	0,   // 71: rpcpb.CoreRPC.Crackstations:input_type -> commonpb.Empty
	39,  // 72: rpcpb.CoreRPC.CrackTaskByID:input_type -> clientpb.CrackTask
	39,  // 73: rpcpb.CoreRPC.CrackTaskUpdate:input_type -> clientpb.CrackTask
	40,  // 74: rpcpb.CoreRPC.CrackFilesList:input_type -> clientpb.CrackFile
	40,  // 75: rpcpb.CoreRPC.CrackFileCreate:input_type -> clientpb.CrackFile
	41,  // 76: rpcpb.CoreRPC.CrackFileChunkUpload:input_type -> clientpb.CrackFileChunk
	41,  // 77: rpcpb.CoreRPC.CrackFileChunkDownload:input_type -> clientpb.CrackFileChunk
	40,  // 78: rpcpb.CoreRPC.CrackFileComplete:input_type -> clientpb.CrackFile
	40,  // 79: rpcpb.CoreRPC.CrackFileDelete:input_type -> clientpb.CrackFile
	42,  // 80: rpcpb.CoreRPC.Regenerate:input_type -> clientpb.RegenerateReq
	0,   // 81: rpcpb.CoreRPC.ImplantBuilds:input_type -> commonpb.Empty
	43,  // 82: rpcpb.CoreRPC.DeleteImplantBuild:input_type -> clientpb.DeleteReq
	0,   // 83: rpcpb.CoreRPC.Canaries:input_type -> commonpb.Empty
	0,   // 84: rpcpb.CoreRPC.GenerateWGClientConfig:input_type -> commonpb.Empty
	0,   // 85: rpcpb.CoreRPC.GenerateUniqueIP:input_type -> commonpb.Empty
	0,   // 86: rpcpb.CoreRPC.ImplantProfiles:input_type -> commonpb.Empty
	43,  // 87: rpcpb.CoreRPC.DeleteImplantProfile:input_type -> clientpb.DeleteReq
	44,  // 88: rpcpb.CoreRPC.SaveImplantProfile:input_type -> clientpb.ImplantProfile
	45,  // 89: rpcpb.CoreRPC.ShellcodeRDI:input_type -> clientpb.ShellcodeRDIReq
	0,   // 90: rpcpb.CoreRPC.GetCompiler:input_type -> commonpb.Empty
	46,  // 91: rpcpb.CoreRPC.ShellcodeEncoder:input_type -> clientpb.ShellcodeEncodeReq
	0,   // 92: rpcpb.CoreRPC.ShellcodeEncoderMap:input_type -> commonpb.Empty
	0,   // 93: rpcpb.CoreRPC.TrafficEncoderMap:input_type -> commonpb.Empty
	47,  // 94: rpcpb.CoreRPC.TrafficEncoderAdd:input_type -> clientpb.TrafficEncoder
	47,  // 95: rpcpb.CoreRPC.TrafficEncoderRm:input_type -> clientpb.TrafficEncoder
	0,   // 96: rpcpb.CoreRPC.Websites:input_type -> commonpb.Empty
	48,  // 97: rpcpb.CoreRPC.Website:input_type -> clientpb.Website
	48,  // 98: rpcpb.CoreRPC.WebsiteRemove:input_type -> clientpb.Website
	49,  // 99: rpcpb.CoreRPC.WebsiteAddContent:input_type -> clientpb.WebsiteAddContent
	49,  // 100: rpcpb.CoreRPC.WebsiteUpdateContent:input_type -> clientpb.WebsiteAddContent
	50,  // 101: rpcpb.CoreRPC.WebsiteRemoveContent:input_type -> clientpb.WebsiteRemoveContent
	51,  // 102: rpcpb.CoreRPC.Ping:input_type -> sudosocpb.Ping
	52,  // 103: rpcpb.CoreRPC.Ps:input_type -> sudosocpb.PsReq
	53,  // 104: rpcpb.CoreRPC.Terminate:input_type -> sudosocpb.TerminateReq
	54,  // 105: rpcpb.CoreRPC.Ifconfig:input_type -> sudosocpb.IfconfigReq
	55,  // 106: rpcpb.CoreRPC.Netstat:input_type -> sudosocpb.NetstatReq
	56,  // 107: rpcpb.CoreRPC.Ls:input_type -> sudosocpb.LsReq
	57,  // 108: rpcpb.CoreRPC.Cd:input_type -> sudosocpb.CdReq
	58,  // 109: rpcpb.CoreRPC.Pwd:input_type -> sudosocpb.PwdReq
	59,  // 110: rpcpb.CoreRPC.Mv:input_type -> sudosocpb.MvReq
	60,  // 111: rpcpb.CoreRPC.Cp:input_type -> sudosocpb.CpReq
	61,  // 112: rpcpb.CoreRPC.Rm:input_type -> sudosocpb.RmReq
	62,  // 113: rpcpb.CoreRPC.Mkdir:input_type -> sudosocpb.MkdirReq
	63,  // 114: rpcpb.CoreRPC.Download:input_type -> sudosocpb.DownloadReq
	64,  // 115: rpcpb.CoreRPC.Upload:input_type -> sudosocpb.UploadReq
	65,  // 116: rpcpb.CoreRPC.Grep:input_type -> sudosocpb.GrepReq
	66,  // 117: rpcpb.CoreRPC.Chmod:input_type -> sudosocpb.ChmodReq
	67,  // 118: rpcpb.CoreRPC.Chown:input_type -> sudosocpb.ChownReq
	68,  // 119: rpcpb.CoreRPC.Chtimes:input_type -> sudosocpb.ChtimesReq
	69,  // 120: rpcpb.CoreRPC.MemfilesList:input_type -> sudosocpb.MemfilesListReq
	70,  // 121: rpcpb.CoreRPC.MemfilesAdd:input_type -> sudosocpb.MemfilesAddReq
	71,  // 122: rpcpb.CoreRPC.MemfilesRm:input_type -> sudosocpb.MemfilesRmReq
	72,  // 123: rpcpb.CoreRPC.Mount:input_type -> sudosocpb.MountReq
	73,  // 124: rpcpb.CoreRPC.ProcessDump:input_type -> sudosocpb.ProcessDumpReq
	74,  // 125: rpcpb.CoreRPC.RunAs:input_type -> sudosocpb.RunAsReq
	75,  // 126: rpcpb.CoreRPC.Impersonate:input_type -> sudosocpb.ImpersonateReq
	76,  // 127: rpcpb.CoreRPC.RevToSelf:input_type -> sudosocpb.RevToSelfReq
	77,  // 128: rpcpb.CoreRPC.GetSystem:input_type -> clientpb.GetSystemReq
	78,  // 129: rpcpb.CoreRPC.Task:input_type -> sudosocpb.TaskReq
	79,  // 130: rpcpb.CoreRPC.Msf:input_type -> clientpb.MSFReq
	80,  // 131: rpcpb.CoreRPC.MsfRemote:input_type -> clientpb.MSFRemoteReq
	81,  // 132: rpcpb.CoreRPC.ExecuteAssembly:input_type -> sudosocpb.ExecuteAssemblyReq
	82,  // 133: rpcpb.CoreRPC.Migrate:input_type -> clientpb.MigrateReq
	83,  // 134: rpcpb.CoreRPC.Execute:input_type -> sudosocpb.ExecuteReq
	84,  // 135: rpcpb.CoreRPC.ExecuteWindows:input_type -> sudosocpb.ExecuteWindowsReq
	85,  // 136: rpcpb.CoreRPC.ExecuteChildren:input_type -> sudosocpb.ExecuteChildrenReq
	86,  // 137: rpcpb.CoreRPC.Sideload:input_type -> sudosocpb.SideloadReq
	87,  // 138: rpcpb.CoreRPC.SpawnDll:input_type -> sudosocpb.InvokeSpawnDllReq
	88,  // 139: rpcpb.CoreRPC.Screenshot:input_type -> sudosocpb.ScreenshotReq
	89,  // 140: rpcpb.CoreRPC.CurrentTokenOwner:input_type -> sudosocpb.CurrentTokenOwnerReq
	90,  // 141: rpcpb.CoreRPC.Services:input_type -> sudosocpb.ServicesReq
	91,  // 142: rpcpb.CoreRPC.ServiceDetail:input_type -> sudosocpb.ServiceDetailReq
	92,  // 143: rpcpb.CoreRPC.StartServiceByName:input_type -> sudosocpb.StartServiceByNameReq
	93,  // 144: rpcpb.CoreRPC.PivotStartListener:input_type -> sudosocpb.PivotStartListenerReq
	94,  // 145: rpcpb.CoreRPC.PivotStopListener:input_type -> sudosocpb.PivotStopListenerReq
	95,  // 146: rpcpb.CoreRPC.PivotSessionListeners:input_type -> sudosocpb.PivotListenersReq
	0,   // 147: rpcpb.CoreRPC.PivotGraph:input_type -> commonpb.Empty
	96,  // 148: rpcpb.CoreRPC.StartService:input_type -> sudosocpb.StartServiceReq
	97,  // 149: rpcpb.CoreRPC.StopService:input_type -> sudosocpb.StopServiceReq
	98,  // 150: rpcpb.CoreRPC.RemoveService:input_type -> sudosocpb.RemoveServiceReq
	99,  // 151: rpcpb.CoreRPC.MakeToken:input_type -> sudosocpb.MakeTokenReq
	100, // 152: rpcpb.CoreRPC.GetEnv:input_type -> sudosocpb.EnvReq
	101, // 153: rpcpb.CoreRPC.SetEnv:input_type -> sudosocpb.SetEnvReq
	102, // 154: rpcpb.CoreRPC.UnsetEnv:input_type -> sudosocpb.UnsetEnvReq
	103, // 155: rpcpb.CoreRPC.Backdoor:input_type -> clientpb.BackdoorReq
	104, // 156: rpcpb.CoreRPC.RegistryRead:input_type -> sudosocpb.RegistryReadReq
	105, // 157: rpcpb.CoreRPC.RegistryWrite:input_type -> sudosocpb.RegistryWriteReq
	106, // 158: rpcpb.CoreRPC.RegistryCreateKey:input_type -> sudosocpb.RegistryCreateKeyReq
	107, // 159: rpcpb.CoreRPC.RegistryDeleteKey:input_type -> sudosocpb.RegistryDeleteKeyReq
	108, // 160: rpcpb.CoreRPC.RegistryListSubKeys:input_type -> sudosocpb.RegistrySubKeyListReq
	109, // 161: rpcpb.CoreRPC.RegistryListValues:input_type -> sudosocpb.RegistryListValuesReq
	110, // 162: rpcpb.CoreRPC.RegistryReadHive:input_type -> sudosocpb.RegistryReadHiveReq
	111, // 163: rpcpb.CoreRPC.RunSSHCommand:input_type -> sudosocpb.SSHCommandReq
	112, // 164: rpcpb.CoreRPC.HijackDLL:input_type -> clientpb.DllHijackReq
	113, // 165: rpcpb.CoreRPC.GetPrivs:input_type -> sudosocpb.GetPrivsReq
	114, // 166: rpcpb.CoreRPC.StartRportFwdListener:input_type -> sudosocpb.RportFwdStartListenerReq
	115, // 167: rpcpb.CoreRPC.GetRportFwdListeners:input_type -> sudosocpb.RportFwdListenersReq
	116, // 168: rpcpb.CoreRPC.StopRportFwdListener:input_type -> sudosocpb.RportFwdStopListenerReq
	117, // 169: rpcpb.CoreRPC.OpenSession:input_type -> sudosocpb.OpenSession
	118, // 170: rpcpb.CoreRPC.CloseSession:input_type -> sudosocpb.CloseSession
	119, // 171: rpcpb.CoreRPC.RegisterExtension:input_type -> sudosocpb.RegisterExtensionReq
	120, // 172: rpcpb.CoreRPC.CallExtension:input_type -> sudosocpb.CallExtensionReq
	121, // 173: rpcpb.CoreRPC.ListExtensions:input_type -> sudosocpb.ListExtensionsReq
	122, // 174: rpcpb.CoreRPC.RegisterWasmExtension:input_type -> sudosocpb.RegisterWasmExtensionReq
	123, // 175: rpcpb.CoreRPC.ListWasmExtensions:input_type -> sudosocpb.ListWasmExtensionsReq
	124, // 176: rpcpb.CoreRPC.ExecWasmExtension:input_type -> sudosocpb.ExecWasmExtensionReq
	125, // 177: rpcpb.CoreRPC.WGStartPortForward:input_type -> sudosocpb.WGPortForwardStartReq
	126, // 178: rpcpb.CoreRPC.WGStopPortForward:input_type -> sudosocpb.WGPortForwardStopReq
	127, // 179: rpcpb.CoreRPC.WGStartSocks:input_type -> sudosocpb.WGSocksStartReq
	128, // 180: rpcpb.CoreRPC.WGStopSocks:input_type -> sudosocpb.WGSocksStopReq
	129, // 181: rpcpb.CoreRPC.WGListForwarders:input_type -> sudosocpb.WGTCPForwardersReq
	130, // 182: rpcpb.CoreRPC.WGListSocksServers:input_type -> sudosocpb.WGSocksServersReq
	131, // 183: rpcpb.CoreRPC.Shell:input_type -> sudosocpb.ShellReq
	132, // 184: rpcpb.CoreRPC.ShellResize:input_type -> sudosocpb.ShellResizeReq
	133, // 185: rpcpb.CoreRPC.Portfwd:input_type -> sudosocpb.PortfwdReq
	134, // 186: rpcpb.CoreRPC.CreateSocks:input_type -> sudosocpb.Socks
	134, // 187: rpcpb.CoreRPC.CloseSocks:input_type -> sudosocpb.Socks
	135, // 188: rpcpb.CoreRPC.SocksProxy:input_type -> sudosocpb.SocksData
	136, // 189: rpcpb.CoreRPC.CreateTunnel:input_type -> sudosocpb.Tunnel
	136, // 190: rpcpb.CoreRPC.CloseTunnel:input_type -> sudosocpb.Tunnel
	137, // 191: rpcpb.CoreRPC.TunnelData:input_type -> sudosocpb.TunnelData
	0,   // 192: rpcpb.CoreRPC.Events:input_type -> commonpb.Empty
	138, // 193: rpcpb.CoreRPC.GetVersion:output_type -> clientpb.Version
	0,   // 194: rpcpb.CoreRPC.ClientLog:output_type -> commonpb.Empty
	139, // 195: rpcpb.CoreRPC.GetOperators:output_type -> clientpb.Operators
	0,   // 196: rpcpb.CoreRPC.Kill:output_type -> commonpb.Empty
	140, // 197: rpcpb.CoreRPC.Reconfigure:output_type -> sudosocpb.Reconfigure
	0,   // 198: rpcpb.CoreRPC.Rename:output_type -> commonpb.Empty
	141, // 199: rpcpb.CoreRPC.GetSessions:output_type -> clientpb.Sessions
	142, // 200: rpcpb.CoreRPC.MonitorStart:output_type -> commonpb.Response
	0,   // 201: rpcpb.CoreRPC.MonitorStop:output_type -> commonpb.Empty
	143, // 202: rpcpb.CoreRPC.MonitorListConfig:output_type -> clientpb.MonitoringProviders
	142, // 203: rpcpb.CoreRPC.MonitorAddConfig:output_type -> commonpb.Response
	142, // 204: rpcpb.CoreRPC.MonitorDelConfig:output_type -> commonpb.Response
	144, // 205: rpcpb.CoreRPC.GetAIProviders:output_type -> clientpb.AIProviderConfigs
	145, // 206: rpcpb.CoreRPC.GetAIConversations:output_type -> clientpb.AIConversations
	7,   // 207: rpcpb.CoreRPC.GetAIConversation:output_type -> clientpb.AIConversation
	7,   // 208: rpcpb.CoreRPC.SaveAIConversation:output_type -> clientpb.AIConversation
	0,   // 209: rpcpb.CoreRPC.DeleteAIConversation:output_type -> commonpb.Empty
	146, // 210: rpcpb.CoreRPC.GetAIConversationMessages:output_type -> clientpb.AIConversationMessages
	8,   // 211: rpcpb.CoreRPC.SaveAIConversationMessage:output_type -> clientpb.AIConversationMessage
	147, // 212: rpcpb.CoreRPC.StartMTLSListener:output_type -> clientpb.ListenerJob
	147, // 213: rpcpb.CoreRPC.StartWGListener:output_type -> clientpb.ListenerJob
	147, // 214: rpcpb.CoreRPC.StartDNSListener:output_type -> clientpb.ListenerJob
	147, // 215: rpcpb.CoreRPC.StartHTTPSListener:output_type -> clientpb.ListenerJob
	147, // 216: rpcpb.CoreRPC.StartHTTPListener:output_type -> clientpb.ListenerJob
	148, // 217: rpcpb.CoreRPC.GetBeacons:output_type -> clientpb.Beacons
	13,  // 218: rpcpb.CoreRPC.GetBeacon:output_type -> clientpb.Beacon
	0,   // 219: rpcpb.CoreRPC.RmBeacon:output_type -> commonpb.Empty
	149, // 220: rpcpb.CoreRPC.GetBeaconTasks:output_type -> clientpb.BeaconTasks
	14,  // 221: rpcpb.CoreRPC.GetBeaconTaskContent:output_type -> clientpb.BeaconTask
	14,  // 222: rpcpb.CoreRPC.CancelBeaconTask:output_type -> clientpb.BeaconTask
	0,   // 223: rpcpb.CoreRPC.UpdateBeaconIntegrityInformation:output_type -> commonpb.Empty
	150, // 224: rpcpb.CoreRPC.GetJobs:output_type -> clientpb.Jobs
	151, // 225: rpcpb.CoreRPC.KillJob:output_type -> clientpb.KillJob
	0,   // 226: rpcpb.CoreRPC.RestartJobs:output_type -> commonpb.Empty
	152, // 227: rpcpb.CoreRPC.StartTCPStagerListener:output_type -> clientpb.StagerListener
	19,  // 228: rpcpb.CoreRPC.LootAdd:output_type -> clientpb.Loot
	0,   // 229: rpcpb.CoreRPC.LootRm:output_type -> commonpb.Empty
	19,  // 230: rpcpb.CoreRPC.LootUpdate:output_type -> clientpb.Loot
	19,  // 231: rpcpb.CoreRPC.LootContent:output_type -> clientpb.Loot
	153, // 232: rpcpb.CoreRPC.LootAll:output_type -> clientpb.AllLoot
	20,  // 233: rpcpb.CoreRPC.Creds:output_type -> clientpb.Credentials
	0,   // 234: rpcpb.CoreRPC.CredsAdd:output_type -> commonpb.Empty
	0,   // 235: rpcpb.CoreRPC.CredsRm:output_type -> commonpb.Empty
	0,   // 236: rpcpb.CoreRPC.CredsUpdate:output_type -> commonpb.Empty
	21,  // 237: rpcpb.CoreRPC.GetCredByID:output_type -> clientpb.Credential
	20,  // 238: rpcpb.CoreRPC.GetCredsByHashType:output_type -> clientpb.Credentials
	20,  // 239: rpcpb.CoreRPC.GetPlaintextCredsByHashType:output_type -> clientpb.Credentials
	21,  // 240: rpcpb.CoreRPC.CredsSniffHashType:output_type -> clientpb.Credential
	154, // 241: rpcpb.CoreRPC.Hosts:output_type -> clientpb.AllHosts
	22,  // 242: rpcpb.CoreRPC.Host:output_type -> clientpb.Host
	0,   // 243: rpcpb.CoreRPC.HostRm:output_type -> commonpb.Empty
	0,   // 244: rpcpb.CoreRPC.HostIOCRm:output_type -> commonpb.Empty
	155, // 245: rpcpb.CoreRPC.Generate:output_type -> clientpb.Generate
	0,   // 246: rpcpb.CoreRPC.GenerateSpoofMetadata:output_type -> commonpb.Empty
	156, // 247: rpcpb.CoreRPC.GenerateExternal:output_type -> clientpb.ExternalImplantConfig
	0,   // 248: rpcpb.CoreRPC.GenerateExternalSaveBuild:output_type -> commonpb.Empty
	156, // 249: rpcpb.CoreRPC.GenerateExternalGetBuildConfig:output_type -> clientpb.ExternalImplantConfig
	155, // 250: rpcpb.CoreRPC.GenerateStage:output_type -> clientpb.Generate
	0,   // 251: rpcpb.CoreRPC.StageImplantBuild:output_type -> commonpb.Empty
	157, // 252: rpcpb.CoreRPC.GetHTTPC2Profiles:output_type -> clientpb.HTTPC2Configs
	158, // 253: rpcpb.CoreRPC.GetHTTPC2ProfileByName:output_type -> clientpb.HTTPC2Config
	0,   // 254: rpcpb.CoreRPC.SaveHTTPC2Profile:output_type -> commonpb.Empty
	34,  // 255: rpcpb.CoreRPC.BuilderRegister:output_type -> clientpb.Event
	0,   // 256: rpcpb.CoreRPC.BuilderTrigger:output_type -> commonpb.Empty
	159, // 257: rpcpb.CoreRPC.Builders:output_type -> clientpb.Builders
	160, // 258: rpcpb.CoreRPC.GetCertificateInfo:output_type -> clientpb.CertificateInfo
	161, // 259: rpcpb.CoreRPC.GetCertificateAuthorityInfo:output_type -> clientpb.CertificateAuthorityInfo
	162, // 260: rpcpb.CoreRPC.Crack:output_type -> clientpb.CrackResponse
	34,  // 261: rpcpb.CoreRPC.CrackstationRegister:output_type -> clientpb.Event
	0,   // 262: rpcpb.CoreRPC.CrackstationTrigger:output_type -> commonpb.Empty
	0,   // 263: rpcpb.CoreRPC.CrackstationBenchmark:output_type -> commonpb.Empty
	163, // 264: rpcpb.CoreRPC.Crackstations:output_type -> clientpb.Crackstations
	39,  // 265: rpcpb.CoreRPC.CrackTaskByID:output_type -> clientpb.CrackTask
	0,   // 266: rpcpb.CoreRPC.CrackTaskUpdate:output_type -> commonpb.Empty
	164, // 267: rpcpb.CoreRPC.CrackFilesList:output_type -> clientpb.CrackFiles
	40,  // 268: rpcpb.CoreRPC.CrackFileCreate:output_type -> clientpb.CrackFile
	0,   // 269: rpcpb.CoreRPC.CrackFileChunkUpload:output_type -> commonpb.Empty
	41,  // 270: rpcpb.CoreRPC.CrackFileChunkDownload:output_type -> clientpb.CrackFileChunk
	0,   // 271: rpcpb.CoreRPC.CrackFileComplete:output_type -> commonpb.Empty
	0,   // 272: rpcpb.CoreRPC.CrackFileDelete:output_type -> commonpb.Empty
	155, // 273: rpcpb.CoreRPC.Regenerate:output_type -> clientpb.Generate
	165, // 274: rpcpb.CoreRPC.ImplantBuilds:output_type -> clientpb.ImplantBuilds
	0,   // 275: rpcpb.CoreRPC.DeleteImplantBuild:output_type -> commonpb.Empty
	166, // 276: rpcpb.CoreRPC.Canaries:output_type -> clientpb.Canaries
	167, // 277: rpcpb.CoreRPC.GenerateWGClientConfig:output_type -> clientpb.WGClientConfig
	168, // 278: rpcpb.CoreRPC.GenerateUniqueIP:output_type -> clientpb.UniqueWGIP
	169, // 279: rpcpb.CoreRPC.ImplantProfiles:output_type -> clientpb.ImplantProfiles
	0,   // 280: rpcpb.CoreRPC.DeleteImplantProfile:output_type -> commonpb.Empty
	44,  // 281: rpcpb.CoreRPC.SaveImplantProfile:output_type -> clientpb.ImplantProfile
	170, // 282: rpcpb.CoreRPC.ShellcodeRDI:output_type -> clientpb.ShellcodeRDI
	171, // 283: rpcpb.CoreRPC.GetCompiler:output_type -> clientpb.Compiler
	172, // 284: rpcpb.CoreRPC.ShellcodeEncoder:output_type -> clientpb.ShellcodeEncode
	173, // 285: rpcpb.CoreRPC.ShellcodeEncoderMap:output_type -> clientpb.ShellcodeEncoderMap
	174, // 286: rpcpb.CoreRPC.TrafficEncoderMap:output_type -> clientpb.TrafficEncoderMap
	175, // 287: rpcpb.CoreRPC.TrafficEncoderAdd:output_type -> clientpb.TrafficEncoderTests
	0,   // 288: rpcpb.CoreRPC.TrafficEncoderRm:output_type -> commonpb.Empty
	176, // 289: rpcpb.CoreRPC.Websites:output_type -> clientpb.Websites
	48,  // 290: rpcpb.CoreRPC.Website:output_type -> clientpb.Website
	0,   // 291: rpcpb.CoreRPC.WebsiteRemove:output_type -> commonpb.Empty
	48,  // 292: rpcpb.CoreRPC.WebsiteAddContent:output_type -> clientpb.Website
	48,  // 293: rpcpb.CoreRPC.WebsiteUpdateContent:output_type -> clientpb.Website
	48,  // 294: rpcpb.CoreRPC.WebsiteRemoveContent:output_type -> clientpb.Website
	51,  // 295: rpcpb.CoreRPC.Ping:output_type -> sudosocpb.Ping
	177, // 296: rpcpb.CoreRPC.Ps:output_type -> sudosocpb.Ps
	178, // 297: rpcpb.CoreRPC.Terminate:output_type -> sudosocpb.Terminate
	179, // 298: rpcpb.CoreRPC.Ifconfig:output_type -> sudosocpb.Ifconfig
	180, // 299: rpcpb.CoreRPC.Netstat:output_type -> sudosocpb.Netstat
	181, // 300: rpcpb.CoreRPC.Ls:output_type -> sudosocpb.Ls
	182, // 301: rpcpb.CoreRPC.Cd:output_type -> sudosocpb.Pwd
	182, // 302: rpcpb.CoreRPC.Pwd:output_type -> sudosocpb.Pwd
	183, // 303: rpcpb.CoreRPC.Mv:output_type -> sudosocpb.Mv
	184, // 304: rpcpb.CoreRPC.Cp:output_type -> sudosocpb.Cp
	185, // 305: rpcpb.CoreRPC.Rm:output_type -> sudosocpb.Rm
	186, // 306: rpcpb.CoreRPC.Mkdir:output_type -> sudosocpb.Mkdir
	187, // 307: rpcpb.CoreRPC.Download:output_type -> sudosocpb.Download
	188, // 308: rpcpb.CoreRPC.Upload:output_type -> sudosocpb.Upload
	189, // 309: rpcpb.CoreRPC.Grep:output_type -> sudosocpb.Grep
	190, // 310: rpcpb.CoreRPC.Chmod:output_type -> sudosocpb.Chmod
	191, // 311: rpcpb.CoreRPC.Chown:output_type -> sudosocpb.Chown
	192, // 312: rpcpb.CoreRPC.Chtimes:output_type -> sudosocpb.Chtimes
	181, // 313: rpcpb.CoreRPC.MemfilesList:output_type -> sudosocpb.Ls
	193, // 314: rpcpb.CoreRPC.MemfilesAdd:output_type -> sudosocpb.MemfilesAdd
	194, // 315: rpcpb.CoreRPC.MemfilesRm:output_type -> sudosocpb.MemfilesRm
	195, // 316: rpcpb.CoreRPC.Mount:output_type -> sudosocpb.Mount
	196, // 317: rpcpb.CoreRPC.ProcessDump:output_type -> sudosocpb.ProcessDump
	197, // 318: rpcpb.CoreRPC.RunAs:output_type -> sudosocpb.RunAs
	198, // 319: rpcpb.CoreRPC.Impersonate:output_type -> sudosocpb.Impersonate
	199, // 320: rpcpb.CoreRPC.RevToSelf:output_type -> sudosocpb.RevToSelf
	200, // 321: rpcpb.CoreRPC.GetSystem:output_type -> sudosocpb.GetSystem
	201, // 322: rpcpb.CoreRPC.Task:output_type -> sudosocpb.Task
	201, // 323: rpcpb.CoreRPC.Msf:output_type -> sudosocpb.Task
	201, // 324: rpcpb.CoreRPC.MsfRemote:output_type -> sudosocpb.Task
	202, // 325: rpcpb.CoreRPC.ExecuteAssembly:output_type -> sudosocpb.ExecuteAssembly
	203, // 326: rpcpb.CoreRPC.Migrate:output_type -> sudosocpb.Migrate
	204, // 327: rpcpb.CoreRPC.Execute:output_type -> sudosocpb.Execute
	204, // 328: rpcpb.CoreRPC.ExecuteWindows:output_type -> sudosocpb.Execute
	205, // 329: rpcpb.CoreRPC.ExecuteChildren:output_type -> sudosocpb.ExecuteChildren
	206, // 330: rpcpb.CoreRPC.Sideload:output_type -> sudosocpb.Sideload
	207, // 331: rpcpb.CoreRPC.SpawnDll:output_type -> sudosocpb.SpawnDll
	208, // 332: rpcpb.CoreRPC.Screenshot:output_type -> sudosocpb.Screenshot
	209, // 333: rpcpb.CoreRPC.CurrentTokenOwner:output_type -> sudosocpb.CurrentTokenOwner
	210, // 334: rpcpb.CoreRPC.Services:output_type -> sudosocpb.Services
	211, // 335: rpcpb.CoreRPC.ServiceDetail:output_type -> sudosocpb.ServiceDetail
	212, // 336: rpcpb.CoreRPC.StartServiceByName:output_type -> sudosocpb.ServiceInfo
	213, // 337: rpcpb.CoreRPC.PivotStartListener:output_type -> sudosocpb.PivotListener
	0,   // 338: rpcpb.CoreRPC.PivotStopListener:output_type -> commonpb.Empty
	214, // 339: rpcpb.CoreRPC.PivotSessionListeners:output_type -> sudosocpb.PivotListeners
	215, // 340: rpcpb.CoreRPC.PivotGraph:output_type -> clientpb.PivotGraph
	212, // 341: rpcpb.CoreRPC.StartService:output_type -> sudosocpb.ServiceInfo
	212, // 342: rpcpb.CoreRPC.StopService:output_type -> sudosocpb.ServiceInfo
	212, // 343: rpcpb.CoreRPC.RemoveService:output_type -> sudosocpb.ServiceInfo
	216, // 344: rpcpb.CoreRPC.MakeToken:output_type -> sudosocpb.MakeToken
	217, // 345: rpcpb.CoreRPC.GetEnv:output_type -> sudosocpb.EnvInfo
	218, // 346: rpcpb.CoreRPC.SetEnv:output_type -> sudosocpb.SetEnv
	219, // 347: rpcpb.CoreRPC.UnsetEnv:output_type -> sudosocpb.UnsetEnv
	220, // 348: rpcpb.CoreRPC.Backdoor:output_type -> clientpb.Backdoor
	221, // 349: rpcpb.CoreRPC.RegistryRead:output_type -> sudosocpb.RegistryRead
	222, // 350: rpcpb.CoreRPC.RegistryWrite:output_type -> sudosocpb.RegistryWrite
	223, // 351: rpcpb.CoreRPC.RegistryCreateKey:output_type -> sudosocpb.RegistryCreateKey
	224, // 352: rpcpb.CoreRPC.RegistryDeleteKey:output_type -> sudosocpb.RegistryDeleteKey
	225, // 353: rpcpb.CoreRPC.RegistryListSubKeys:output_type -> sudosocpb.RegistrySubKeyList
	226, // 354: rpcpb.CoreRPC.RegistryListValues:output_type -> sudosocpb.RegistryValuesList
	227, // 355: rpcpb.CoreRPC.RegistryReadHive:output_type -> sudosocpb.RegistryReadHive
	228, // 356: rpcpb.CoreRPC.RunSSHCommand:output_type -> sudosocpb.SSHCommand
	229, // 357: rpcpb.CoreRPC.HijackDLL:output_type -> clientpb.DllHijack
	230, // 358: rpcpb.CoreRPC.GetPrivs:output_type -> sudosocpb.GetPrivs
	231, // 359: rpcpb.CoreRPC.StartRportFwdListener:output_type -> sudosocpb.RportFwdListener
	232, // 360: rpcpb.CoreRPC.GetRportFwdListeners:output_type -> sudosocpb.RportFwdListeners
	231, // 361: rpcpb.CoreRPC.StopRportFwdListener:output_type -> sudosocpb.RportFwdListener
	117, // 362: rpcpb.CoreRPC.OpenSession:output_type -> sudosocpb.OpenSession
	0,   // 363: rpcpb.CoreRPC.CloseSession:output_type -> commonpb.Empty
	233, // 364: rpcpb.CoreRPC.RegisterExtension:output_type -> sudosocpb.RegisterExtension
	234, // 365: rpcpb.CoreRPC.CallExtension:output_type -> sudosocpb.CallExtension
	235, // 366: rpcpb.CoreRPC.ListExtensions:output_type -> sudosocpb.ListExtensions
	236, // 367: rpcpb.CoreRPC.RegisterWasmExtension:output_type -> sudosocpb.RegisterWasmExtension
	237, // 368: rpcpb.CoreRPC.ListWasmExtensions:output_type -> sudosocpb.ListWasmExtensions
	238, // 369: rpcpb.CoreRPC.ExecWasmExtension:output_type -> sudosocpb.ExecWasmExtension
	239, // 370: rpcpb.CoreRPC.WGStartPortForward:output_type -> sudosocpb.WGPortForward
	239, // 371: rpcpb.CoreRPC.WGStopPortForward:output_type -> sudosocpb.WGPortForward
	240, // 372: rpcpb.CoreRPC.WGStartSocks:output_type -> sudosocpb.WGSocks
	240, // 373: rpcpb.CoreRPC.WGStopSocks:output_type -> sudosocpb.WGSocks
	241, // 374: rpcpb.CoreRPC.WGListForwarders:output_type -> sudosocpb.WGTCPForwarders
	242, // 375: rpcpb.CoreRPC.WGListSocksServers:output_type -> sudosocpb.WGSocksServers
	243, // 376: rpcpb.CoreRPC.Shell:output_type -> sudosocpb.Shell
	0,   // 377: rpcpb.CoreRPC.ShellResize:output_type -> commonpb.Empty
	244, // 378: rpcpb.CoreRPC.Portfwd:output_type -> sudosocpb.Portfwd
	134, // 379: rpcpb.CoreRPC.CreateSocks:output_type -> sudosocpb.Socks
	0,   // 380: rpcpb.CoreRPC.CloseSocks:output_type -> commonpb.Empty
	135, // 381: rpcpb.CoreRPC.SocksProxy:output_type -> sudosocpb.SocksData
	136, // 382: rpcpb.CoreRPC.CreateTunnel:output_type -> sudosocpb.Tunnel
	0,   // 383: rpcpb.CoreRPC.CloseTunnel:output_type -> commonpb.Empty
	137, // 384: rpcpb.CoreRPC.TunnelData:output_type -> sudosocpb.TunnelData
	34,  // 385: rpcpb.CoreRPC.Events:output_type -> clientpb.Event
	193, // [193:386] is the sub-list for method output_type
	0,   // [0:193] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_services_proto_init() }
func file_rpcpb_services_proto_init() {
	if File_rpcpb_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_services_proto_rawDesc), len(file_rpcpb_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_services_proto_goTypes,
		DependencyIndexes: file_rpcpb_services_proto_depIdxs,
	}.Build()
	File_rpcpb_services_proto = out.File
	file_rpcpb_services_proto_goTypes = nil
	file_rpcpb_services_proto_depIdxs = nil
}
